// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/api-error.json

/// Error body returned with any non-2xx status.
class ApiError {
  const ApiError({
    required this.code,
    required this.message,
  });

  factory ApiError.fromJson(Map<String, dynamic> json) => ApiError(
    code: json['code'] as String,
    message: json['message'] as String,
  );

  /// Stable machine-readable code, e.g. `not_found`, `sha256_mismatch`, `tag_not_found`,
  /// `unauthorized`, `org_taken`.
  final String code;

  final String message;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'code': code,
    'message': message,
  };
}
