// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/audit-log-response.json

/// A state-changing action recorded in an org's audit log. Reads are never audited — only
/// mutations of published state and of the namespace itself, so the log answers "who
/// changed what" without drowning in traffic.
enum AuditAction {
  /// A version was published.
  publish('publish'),
  /// A version was yanked (hidden from fresh resolution).
  yank('yank'),
  /// A previously yanked version was restored.
  unyank('unyank'),
  /// The org namespace was claimed.
  orgClaim('org_claim');

  const AuditAction(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static AuditAction fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown AuditAction: $value'),
  );

  static AuditAction? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}

/// One audit-log record. The actor is identified by the *token* that acted — its name and
/// role, never its secret — which is the identity a registry actually has (zed-docs issue
/// #7 governance).
class AuditEntry {
  const AuditEntry({
    required this.action,
    this.actionKind,
    required this.actorRole,
    required this.actorTokenName,
    required this.at,
    this.detail,
    this.entryHash,
    this.prevHash,
    this.seq = 0,
    required this.subject,
  });

  factory AuditEntry.fromJson(Map<String, dynamic> json) => AuditEntry(
    action: json['action'] as String,
    actionKind: AuditAction.maybeFromJson(json['action_kind'] as String?),
    actorRole: json['actor_role'] as String,
    actorTokenName: json['actor_token_name'] as String,
    at: json['at'] as String,
    detail: json['detail'] as String?,
    entryHash: json['entry_hash'] as String?,
    prevHash: json['prev_hash'] as String?,
    seq: json['seq'] == null
        ? 0
        : (json['seq'] as num).toInt(),
    subject: json['subject'] as String,
  );

  /// Raw action string; `action_kind` is the parsed form when recognized.
  final String action;

  /// Parsed action, absent when this server build doesn't recognize it.
  final AuditAction? actionKind;

  /// The acting token's role (`owner`/`publisher`/`reader`, or `admin` for unscoped tokens).
  final String actorRole;

  /// Human-readable name of the token that acted.
  final String actorTokenName;

  /// RFC 3339 timestamp of the action.
  final String at;

  /// Extra context, e.g. the artifact sha256 for a publish.
  final String? detail;

  /// `sha256(audit_chain_preimage(..))` for this entry, lowercase hex. Empty from a pre-chain
  /// server.
  final String? entryHash;

  /// The previous entry's `entry_hash`; `None` for the first entry in an org's chain. Linking
  /// each entry to its predecessor is what makes a silent deletion or edit detectable.
  final String? prevHash;

  /// Position in the org's append-only chain, starting at 1. Gaps mean entries were deleted.
  /// Defaults to 0 when read from a server that predates the chain.
  final int seq;

  /// What was acted on, e.g. `acme/http-kit@1.2.0` or the org slug.
  final String subject;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'action': action,
    'action_kind': actionKind?.toJson(),
    'actor_role': actorRole,
    'actor_token_name': actorTokenName,
    'at': at,
    'detail': detail,
    'entry_hash': entryHash,
    'prev_hash': prevHash,
    'seq': seq,
    'subject': subject,
  };
}

class AuditLogResponse {
  const AuditLogResponse({
    required this.entries,
    required this.org,
  });

  factory AuditLogResponse.fromJson(Map<String, dynamic> json) => AuditLogResponse(
    entries: (json['entries'] as List<dynamic>).map((e) => AuditEntry.fromJson(e as Map<String, dynamic>)).toList(),
    org: json['org'] as String,
  );

  /// Most recent first.
  final List<AuditEntry> entries;

  final String org;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'entries': entries.map((e) => e.toJson()).toList(),
    'org': org,
  };
}
