// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/audit-integrity-response.json

/// The result of walking an org's audit chain end to end.
class AuditIntegrityResponse {
  const AuditIntegrityResponse({
    required this.entriesChecked,
    this.firstBadSeq,
    this.headHash,
    required this.intact,
    required this.org,
    this.problem,
  });

  factory AuditIntegrityResponse.fromJson(Map<String, dynamic> json) => AuditIntegrityResponse(
    entriesChecked: (json['entries_checked'] as num).toInt(),
    firstBadSeq: (json['first_bad_seq'] as num?)?.toInt(),
    headHash: json['head_hash'] as String?,
    intact: json['intact'] as bool,
    org: json['org'] as String,
    problem: json['problem'] as String?,
  );

  final int entriesChecked;

  /// The `seq` where verification first failed, if any.
  final int? firstBadSeq;

  /// The newest entry's hash — an anchor an operator can record externally so that later
  /// truncation of the whole tail is also detectable.
  final String? headHash;

  /// True only when every entry's hash recomputes and every link matches.
  final bool intact;

  final String org;

  /// Machine-readable failure kind: `hash_mismatch` (an entry was edited), `broken_link` (an
  /// entry's `prev_hash` does not match its predecessor), or `sequence_gap` (an entry was
  /// deleted).
  final String? problem;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'entries_checked': entriesChecked,
    'first_bad_seq': firstBadSeq,
    'head_hash': headHash,
    'intact': intact,
    'org': org,
    'problem': problem,
  };
}
