// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/binary-artifact-list-v1.json

import 'common.dart';

/// Collection response for every target/format artifact of one release.
class BinaryArtifactListResponseV1 {
  const BinaryArtifactListResponseV1({
    required this.artifacts,
    required this.name,
    required this.org,
    required this.schema,
    required this.version,
  });

  factory BinaryArtifactListResponseV1.fromJson(Map<String, dynamic> json) => BinaryArtifactListResponseV1(
    artifacts: (json['artifacts'] as List<dynamic>).map((e) => BinaryArtifactMetadataV1.fromJson(e as Map<String, dynamic>)).toList(),
    name: json['name'] as String,
    org: json['org'] as String,
    schema: json['schema'] as String,
    version: json['version'] as String,
  );

  /// Strictly sorted by `(platform.target, format)` with no duplicates.
  final List<BinaryArtifactMetadataV1> artifacts;

  final String name;

  final String org;

  final String schema;

  final String version;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'artifacts': artifacts.map((e) => e.toJson()).toList(),
    'name': name,
    'org': org,
    'schema': schema,
    'version': version,
  };
}
