// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/claim-org-response.json

class ClaimOrgResponse {
  const ClaimOrgResponse({
    required this.created,
    required this.slug,
  });

  factory ClaimOrgResponse.fromJson(Map<String, dynamic> json) => ClaimOrgResponse(
    created: json['created'] as bool,
    slug: json['slug'] as String,
  );

  /// False when the caller already owned the org.
  final bool created;

  final String slug;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'created': created,
    'slug': slug,
  };
}
