// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/claim-org-request.json

class ClaimOrgRequest {
  const ClaimOrgRequest({
    required this.slug,
  });

  factory ClaimOrgRequest.fromJson(Map<String, dynamic> json) => ClaimOrgRequest(
    slug: json['slug'] as String,
  );

  final String slug;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'slug': slug,
  };
}
