// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: types shared by more than one schema

class PackageSummary {
  const PackageSummary({
    this.description,
    this.latest,
    required this.name_,
    required this.org,
    this.tags,
  });

  factory PackageSummary.fromJson(Map<String, dynamic> json) => PackageSummary(
          description: json["description"] == null ? null : json["description"] as String,
          latest: json["latest"] == null ? null : json["latest"] as String,
          name_: json["name"] as String,
          org: json["org"] as String,
          tags: json["tags"] == null ? null : (json["tags"] as List<dynamic>).map((e) => e as String).toList(),
      );

  final String? description;

  final String? latest;

  final String name_;

  final String org;

  /// Free-form tags for filtering/discovery.
  final List<String>? tags;

  Map<String, dynamic> toJson() => <String, dynamic>{
        "description": description,
        "latest": latest,
        "name": name_,
        "org": org,
        "tags": tags,
      };
}
