// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/inspection-report.json

class InspectedLockedPackage {
  const InspectedLockedPackage({
    required this.materialized,
    required this.name,
    required this.org,
    required this.sha256,
    this.storePresent,
    required this.version,
  });

  factory InspectedLockedPackage.fromJson(Map<String, dynamic> json) => InspectedLockedPackage(
    materialized: json['materialized'] as bool,
    name: json['name'] as String,
    org: json['org'] as String,
    sha256: json['sha256'] as String,
    storePresent: json['store_present'] as bool?,
    version: json['version'] as String,
  );

  final bool materialized;

  final String name;

  final String org;

  final String sha256;

  final bool? storePresent;

  final String version;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'materialized': materialized,
    'name': name,
    'org': org,
    'sha256': sha256,
    'store_present': storePresent,
    'version': version,
  };
}

class InspectedPackageIdentity {
  const InspectedPackageIdentity({
    required this.name,
    required this.org,
    required this.version,
  });

  factory InspectedPackageIdentity.fromJson(Map<String, dynamic> json) => InspectedPackageIdentity(
    name: json['name'] as String,
    org: json['org'] as String,
    version: json['version'] as String,
  );

  final String name;

  final String org;

  final String version;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'name': name,
    'org': org,
    'version': version,
  };
}

class InspectedPackageState {
  const InspectedPackageState({
    this.identity,
    required this.lockfile,
    required this.manifest,
    required this.materializationDir,
  });

  factory InspectedPackageState.fromJson(Map<String, dynamic> json) => InspectedPackageState(
    identity: json['identity'] == null ? null : InspectedPackageIdentity.fromJson(json['identity'] as Map<String, dynamic>),
    lockfile: json['lockfile'] as String,
    manifest: json['manifest'] as String,
    materializationDir: json['materialization_dir'] as String,
  );

  final InspectedPackageIdentity? identity;

  final String lockfile;

  final String manifest;

  final String materializationDir;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'identity': identity?.toJson(),
    'lockfile': lockfile,
    'manifest': manifest,
    'materialization_dir': materializationDir,
  };
}

enum InspectionActionKind {
  zedCommand('zed-command');

  const InspectionActionKind(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static InspectionActionKind fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown InspectionActionKind: $value'),
  );

  static InspectionActionKind? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}

class InspectionAdapterOutput {
  const InspectionAdapterOutput({
    required this.kind,
    required this.path,
    required this.present,
  });

  factory InspectionAdapterOutput.fromJson(Map<String, dynamic> json) => InspectionAdapterOutput(
    kind: json['kind'] as String,
    path: json['path'] as String,
    present: json['present'] as bool,
  );

  final String kind;

  final String path;

  final bool present;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'kind': kind,
    'path': path,
    'present': present,
  };
}

class InspectionCliIdentity {
  const InspectionCliIdentity({
    required this.command,
    required this.implementation,
    required this.loadsCredentials,
    required this.mutatesProject,
    required this.offline,
  });

  factory InspectionCliIdentity.fromJson(Map<String, dynamic> json) => InspectionCliIdentity(
    command: json['command'] as String,
    implementation: json['implementation'] as String,
    loadsCredentials: json['loads_credentials'] as bool,
    mutatesProject: json['mutates_project'] as bool,
    offline: json['offline'] as bool,
  );

  final String command;

  final String implementation;

  final bool loadsCredentials;

  final bool mutatesProject;

  final bool offline;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'command': command,
    'implementation': implementation,
    'loads_credentials': loadsCredentials,
    'mutates_project': mutatesProject,
    'offline': offline,
  };
}

class InspectionDiagnostic {
  const InspectionDiagnostic({
    this.actions,
    required this.code,
    this.detail,
    required this.location,
    required this.message,
    required this.severity,
  });

  factory InspectionDiagnostic.fromJson(Map<String, dynamic> json) => InspectionDiagnostic(
    actions: (json['actions'] as List<dynamic>?)?.map((e) => InspectionRecommendedAction.fromJson(e as Map<String, dynamic>)).toList(),
    code: json['code'] as String,
    detail: json['detail'] as String?,
    location: InspectionLocation.fromJson(json['location'] as Map<String, dynamic>),
    message: json['message'] as String,
    severity: InspectionSeverity.fromJson(json['severity'] as String),
  );

  final List<InspectionRecommendedAction>? actions;

  final String code;

  final String? detail;

  final InspectionLocation location;

  final String message;

  final InspectionSeverity severity;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'actions': actions?.map((e) => e.toJson()).toList(),
    'code': code,
    'detail': detail,
    'location': location.toJson(),
    'message': message,
    'severity': severity.toJson(),
  };
}

enum InspectionHealth {
  healthy('healthy'),
  warning('warning'),
  error('error');

  const InspectionHealth(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static InspectionHealth fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown InspectionHealth: $value'),
  );

  static InspectionHealth? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}

class InspectionLocation {
  const InspectionLocation({
    this.column,
    this.line,
    required this.path,
  });

  factory InspectionLocation.fromJson(Map<String, dynamic> json) => InspectionLocation(
    column: (json['column'] as num?)?.toInt(),
    line: (json['line'] as num?)?.toInt(),
    path: json['path'] as String,
  );

  final int? column;

  final int? line;

  final String path;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'column': column,
    'line': line,
    'path': path,
  };
}

class InspectionRecommendedAction {
  const InspectionRecommendedAction({
    required this.argv,
    required this.cwd,
    required this.executesPackageCode,
    required this.id,
    required this.kind,
    required this.mutatesProject,
    required this.requiresNetwork,
    required this.title,
  });

  factory InspectionRecommendedAction.fromJson(Map<String, dynamic> json) => InspectionRecommendedAction(
    argv: (json['argv'] as List<dynamic>).map((e) => e as String).toList(),
    cwd: json['cwd'] as String,
    executesPackageCode: json['executes_package_code'] as bool,
    id: json['id'] as String,
    kind: InspectionActionKind.fromJson(json['kind'] as String),
    mutatesProject: json['mutates_project'] as bool,
    requiresNetwork: json['requires_network'] as bool,
    title: json['title'] as String,
  );

  final List<String> argv;

  final String cwd;

  final bool executesPackageCode;

  final String id;

  final InspectionActionKind kind;

  final bool mutatesProject;

  final bool requiresNetwork;

  final String title;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'argv': argv,
    'cwd': cwd,
    'executes_package_code': executesPackageCode,
    'id': id,
    'kind': kind.toJson(),
    'mutates_project': mutatesProject,
    'requires_network': requiresNetwork,
    'title': title,
  };
}

class InspectionReport {
  const InspectionReport({
    required this.adapterOutputs,
    required this.cli,
    required this.diagnostics,
    required this.interop,
    required this.lockedPackages,
    required this.package,
    required this.root,
    required this.schemaVersion,
    required this.summary,
    required this.workspaceMembers,
  });

  factory InspectionReport.fromJson(Map<String, dynamic> json) => InspectionReport(
    adapterOutputs: (json['adapter_outputs'] as List<dynamic>).map((e) => InspectionAdapterOutput.fromJson(e as Map<String, dynamic>)).toList(),
    cli: InspectionCliIdentity.fromJson(json['cli'] as Map<String, dynamic>),
    diagnostics: (json['diagnostics'] as List<dynamic>).map((e) => InspectionDiagnostic.fromJson(e as Map<String, dynamic>)).toList(),
    interop: InteropInspection.fromJson(json['interop'] as Map<String, dynamic>),
    lockedPackages: (json['locked_packages'] as List<dynamic>).map((e) => InspectedLockedPackage.fromJson(e as Map<String, dynamic>)).toList(),
    package: InspectedPackageState.fromJson(json['package'] as Map<String, dynamic>),
    root: json['root'] as String,
    schemaVersion: json['schema_version'] as String,
    summary: InspectionSummary.fromJson(json['summary'] as Map<String, dynamic>),
    workspaceMembers: (json['workspace_members'] as List<dynamic>).map((e) => e as String).toList(),
  );

  final List<InspectionAdapterOutput> adapterOutputs;

  final InspectionCliIdentity cli;

  final List<InspectionDiagnostic> diagnostics;

  final InteropInspection interop;

  final List<InspectedLockedPackage> lockedPackages;

  final InspectedPackageState package;

  final String root;

  final String schemaVersion;

  final InspectionSummary summary;

  final List<String> workspaceMembers;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'adapter_outputs': adapterOutputs.map((e) => e.toJson()).toList(),
    'cli': cli.toJson(),
    'diagnostics': diagnostics.map((e) => e.toJson()).toList(),
    'interop': interop.toJson(),
    'locked_packages': lockedPackages.map((e) => e.toJson()).toList(),
    'package': package.toJson(),
    'root': root,
    'schema_version': schemaVersion,
    'summary': summary.toJson(),
    'workspace_members': workspaceMembers,
  };
}

enum InspectionSeverity {
  error('error'),
  warning('warning'),
  info('info');

  const InspectionSeverity(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static InspectionSeverity fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown InspectionSeverity: $value'),
  );

  static InspectionSeverity? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}

class InspectionSummary {
  const InspectionSummary({
    required this.errors,
    required this.frozenReady,
    required this.health,
    required this.recoveryPending,
    required this.warnings,
  });

  factory InspectionSummary.fromJson(Map<String, dynamic> json) => InspectionSummary(
    errors: (json['errors'] as num).toInt(),
    frozenReady: json['frozen_ready'] as bool,
    health: InspectionHealth.fromJson(json['health'] as String),
    recoveryPending: json['recovery_pending'] as bool,
    warnings: (json['warnings'] as num).toInt(),
  );

  final int errors;

  final bool frozenReady;

  final InspectionHealth health;

  final bool recoveryPending;

  final int warnings;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'errors': errors,
    'frozen_ready': frozenReady,
    'health': health.toJson(),
    'recovery_pending': recoveryPending,
    'warnings': warnings,
  };
}

class InteropInspection {
  const InteropInspection({
    required this.gitSubmodules,
    required this.mise,
    required this.nixDevelop,
  });

  factory InteropInspection.fromJson(Map<String, dynamic> json) => InteropInspection(
    gitSubmodules: InteropStatus.fromJson(json['git_submodules'] as Map<String, dynamic>),
    mise: InteropStatus.fromJson(json['mise'] as Map<String, dynamic>),
    nixDevelop: InteropStatus.fromJson(json['nix_develop'] as Map<String, dynamic>),
  );

  final InteropStatus gitSubmodules;

  final InteropStatus mise;

  final InteropStatus nixDevelop;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'git_submodules': gitSubmodules.toJson(),
    'mise': mise.toJson(),
    'nix_develop': nixDevelop.toJson(),
  };
}

class InteropStatus {
  const InteropStatus({
    required this.declared,
    required this.detected,
    this.source,
    required this.verified,
  });

  factory InteropStatus.fromJson(Map<String, dynamic> json) => InteropStatus(
    declared: json['declared'] as bool,
    detected: json['detected'] as bool,
    source: json['source'] as String?,
    verified: json['verified'] as bool,
  );

  final bool declared;

  final bool detected;

  final String? source;

  final bool verified;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'declared': declared,
    'detected': detected,
    'source': source,
    'verified': verified,
  };
}
