// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/mirrors-response.json

import 'common.dart';

/// Response for `GET /v1/mirrors` and the well-known bootstrap path.
class MirrorsResponse {
  const MirrorsResponse({
    required this.mirrors,
    required this.registryUrl,
  });

  factory MirrorsResponse.fromJson(Map<String, dynamic> json) => MirrorsResponse(
    mirrors: (json['mirrors'] as List<dynamic>).map((e) => MirrorDescriptorV1.fromJson(e as Map<String, dynamic>)).toList(),
    registryUrl: json['registry_url'] as String,
  );

  final List<MirrorDescriptorV1> mirrors;

  final String registryUrl;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'mirrors': mirrors.map((e) => e.toJson()).toList(),
    'registry_url': registryUrl,
  };
}
