// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/mirror-descriptor-v1.json

export 'common.dart' show MirrorDescriptorV1;
