// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/mirror-bootstrap-v1.json

import 'common.dart';

/// The document served at [`MIRROR_BOOTSTRAP_PATH`]. Deliberately small and
/// unsigned-optional: its only job is to name hosts. A hostile bootstrap can send a client
/// to a mirror of its choosing, and that mirror still cannot produce bytes matching the
/// lockfile pin, nor metadata carrying a publisher signature it does not have.
class MirrorBootstrapV1 {
  const MirrorBootstrapV1({
    required this.generatedAt,
    required this.mirrors,
    required this.registryUrl,
    required this.schema,
  });

  factory MirrorBootstrapV1.fromJson(Map<String, dynamic> json) => MirrorBootstrapV1(
    generatedAt: json['generated_at'] as String,
    mirrors: (json['mirrors'] as List<dynamic>).map((e) => MirrorDescriptorV1.fromJson(e as Map<String, dynamic>)).toList(),
    registryUrl: json['registry_url'] as String,
    schema: json['schema'] as String,
  );

  /// RFC 3339 timestamp this document was generated.
  final String generatedAt;

  /// Every mirror the operator publishes, in try order.
  final List<MirrorDescriptorV1> mirrors;

  /// Canonical registry base URL, for clients that recover mid-outage.
  final String registryUrl;

  final String schema;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'generated_at': generatedAt,
    'mirrors': mirrors.map((e) => e.toJson()).toList(),
    'registry_url': registryUrl,
    'schema': schema,
  };
}
