// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/org-keys-response.json

import 'common.dart';

/// Response for `GET /v1/orgs/{org}/keys`.
class OrgKeysResponse {
  const OrgKeysResponse({
    required this.keys,
    required this.org,
  });

  factory OrgKeysResponse.fromJson(Map<String, dynamic> json) => OrgKeysResponse(
    keys: (json['keys'] as List<dynamic>).map((e) => PublisherKeyV1.fromJson(e as Map<String, dynamic>)).toList(),
    org: json['org'] as String,
  );

  final List<PublisherKeyV1> keys;

  final String org;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'keys': keys.map((e) => e.toJson()).toList(),
    'org': org,
  };
}
