// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/package-list-response.json

import 'common.dart';

/// Response for `GET /v1/packages` (list all).
class PackageListResponse {
  const PackageListResponse({
    required this.items,
    required this.total,
  });

  factory PackageListResponse.fromJson(Map<String, dynamic> json) => PackageListResponse(
    items: (json['items'] as List<dynamic>).map((e) => PackageSummary.fromJson(e as Map<String, dynamic>)).toList(),
    total: (json['total'] as num).toInt(),
  );

  final List<PackageSummary> items;

  /// Total packages matching the filter (before limit/offset).
  final int total;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'items': items.map((e) => e.toJson()).toList(),
    'total': total,
  };
}
