// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/package-metadata.json

class PackageMetadata {
  const PackageMetadata({
    this.description,
    this.latest,
    required this.name,
    required this.org,
    required this.repoUrl,
    this.tags,
    required this.vcs,
    this.versionScheme,
    required this.versions,
  });

  factory PackageMetadata.fromJson(Map<String, dynamic> json) => PackageMetadata(
    description: json['description'] as String?,
    latest: json['latest'] as String?,
    name: json['name'] as String,
    org: json['org'] as String,
    repoUrl: json['repo_url'] as String,
    tags: (json['tags'] as List<dynamic>?)?.map((e) => e as String).toList(),
    vcs: Vcs.fromJson(json['vcs'] as String),
    versionScheme: VersionScheme.maybeFromJson(json['version_scheme'] as String?),
    versions: (json['versions'] as List<dynamic>).map((e) => e as String).toList(),
  );

  final String? description;

  final String? latest;

  final String name;

  final String org;

  final String repoUrl;

  /// Free-form tags for filtering/discovery (multi-tag lookup).
  final List<String>? tags;

  final Vcs vcs;

  /// How this package's versions should be interpreted (semver by default).
  final VersionScheme? versionScheme;

  /// All published, non-yanked versions, newest first.
  final List<String> versions;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'description': description,
    'latest': latest,
    'name': name,
    'org': org,
    'repo_url': repoUrl,
    'tags': tags,
    'vcs': vcs.toJson(),
    'version_scheme': versionScheme?.toJson(),
    'versions': versions,
  };
}

/// Version-control systems a package's source repository can live on. zed-pkg is
/// VCS-agnostic by design: what gets installed is always a registry artifact, and the VCS
/// is where provenance (tags) is anchored. Authors must create a matching tag on their
/// declared backing repo (GitHub, GitLab, Bitbucket, Codeberg, SourceHut, Forgejo, Gitea,
/// Azure DevOps, CodeCommit, Radicle, or self-hosted) before publishing. `jj` and Sapling
/// are git-compatible and push to git remotes, so their provenance is verified through git
/// tags.
enum Vcs {
  git('git'),
  hg('hg'),
  jj('jj'),
  sapling('sapling'),
  fossil('fossil'),
  pijul('pijul');

  const Vcs(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static Vcs fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown Vcs: $value'),
  );

  static Vcs? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}

/// How a package's `version` string (and its published tags) should be interpreted.
/// Defaults to [`VersionScheme::Semver`], which covers the vast majority of modern
/// ecosystems.
enum VersionScheme {
  /// Semantic Versioning. `package.version` must be valid semver; ranges (`^1.2`, `>=0.2
  /// <0.5`) resolve to the max satisfying stable version.
  semver('semver'),
  /// Calendar Versioning (`2026.07.24`, `2026.07`). Normalized to a semver total order
  /// (leading zeros dropped, padded to major.minor.patch) so the same range algebra applies.
  /// See [`normalize_calver`].
  calver('calver'),
  /// Arbitrary tags (`release-candidate-1`, `legacy-api`). No range algebra: a requirement
  /// must match a published version **exactly**.
  opaque('opaque');

  const VersionScheme(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static VersionScheme fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown VersionScheme: $value'),
  );

  static VersionScheme? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}
