// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/pre-interest-registration-request-v1.json

import 'common.dart';

/// Register interest without creating an account, quote, organization, or authenticated
/// session.
class PreInterestRegistrationRequestV1 {
  const PreInterestRegistrationRequestV1({
    required this.consentRevision,
    required this.consentedAt,
    required this.contactConsent,
    this.contactName,
    required this.email,
    required this.interests,
    this.locale,
    required this.marketingConsent,
    this.marketingConsentRevision,
    this.organizationName,
    required this.partyType,
    this.referralCode,
    required this.requestId,
    required this.schema,
    required this.sourceHost,
    this.websiteUrl,
  });

  factory PreInterestRegistrationRequestV1.fromJson(Map<String, dynamic> json) => PreInterestRegistrationRequestV1(
    consentRevision: json['consentRevision'] as String,
    consentedAt: json['consentedAt'] as String,
    contactConsent: json['contactConsent'] as bool,
    contactName: json['contactName'] as String?,
    email: json['email'] as String,
    interests: (json['interests'] as List<dynamic>).map((e) => PublicIntakeInterestV1.fromJson(e as String)).toList(),
    locale: json['locale'] as String?,
    marketingConsent: json['marketingConsent'] as bool,
    marketingConsentRevision: json['marketingConsentRevision'] as String?,
    organizationName: json['organizationName'] as String?,
    partyType: PublicIntakePartyV1.fromJson(json['partyType'] as String),
    referralCode: json['referralCode'] as String?,
    requestId: json['requestId'] as String,
    schema: PublicIntakeSchemaV1.fromJson(json['schema'] as String),
    sourceHost: PublicIntakeSourceHostV1.fromJson(json['sourceHost'] as String),
    websiteUrl: json['websiteUrl'] as String?,
  );

  final String consentRevision;

  /// RFC 3339 timestamp supplied by the browser and bounded by domain validation against
  /// server time.
  final String consentedAt;

  /// Must be true after validation. This is consent to store and contact, not account
  /// creation and not marketing consent.
  final bool contactConsent;

  final String? contactName;

  final String email;

  final List<PublicIntakeInterestV1> interests;

  final String? locale;

  final bool marketingConsent;

  final String? marketingConsentRevision;

  final String? organizationName;

  final PublicIntakePartyV1 partyType;

  final String? referralCode;

  /// Client-generated UUID used together with `Idempotency-Key`. It is not returned from the
  /// public endpoint.
  final String requestId;

  final PublicIntakeSchemaV1 schema;

  final PublicIntakeSourceHostV1 sourceHost;

  final String? websiteUrl;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'consentRevision': consentRevision,
    'consentedAt': consentedAt,
    'contactConsent': contactConsent,
    'contactName': contactName,
    'email': email,
    'interests': interests.map((e) => e.toJson()).toList(),
    'locale': locale,
    'marketingConsent': marketingConsent,
    'marketingConsentRevision': marketingConsentRevision,
    'organizationName': organizationName,
    'partyType': partyType.toJson(),
    'referralCode': referralCode,
    'requestId': requestId,
    'schema': schema.toJson(),
    'sourceHost': sourceHost.toJson(),
    'websiteUrl': websiteUrl,
  };
}

enum PublicIntakePartyV1 {
  individual('individual'),
  organization('organization');

  const PublicIntakePartyV1(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static PublicIntakePartyV1 fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown PublicIntakePartyV1: $value'),
  );

  static PublicIntakePartyV1? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}
