// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/public-intake-error-v1.json

import 'common.dart';

enum PublicIntakeErrorCodeV1 {
  invalidRequest('invalid_request'),
  unsupportedMediaType('unsupported_media_type'),
  payloadTooLarge('payload_too_large'),
  abuseChallengeFailed('abuse_challenge_failed'),
  rateLimited('rate_limited'),
  temporarilyUnavailable('temporarily_unavailable');

  const PublicIntakeErrorCodeV1(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static PublicIntakeErrorCodeV1 fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown PublicIntakeErrorCodeV1: $value'),
  );

  static PublicIntakeErrorCodeV1? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}

/// Closed public error categories. No arbitrary detail or reflected input is present in the
/// wire shape; operational detail belongs only in redacted internal telemetry keyed by a
/// server-generated trace identifier.
class PublicIntakeErrorV1 {
  const PublicIntakeErrorV1({
    required this.code,
    required this.retryable,
    required this.schema,
  });

  factory PublicIntakeErrorV1.fromJson(Map<String, dynamic> json) => PublicIntakeErrorV1(
    code: PublicIntakeErrorCodeV1.fromJson(json['code'] as String),
    retryable: json['retryable'] as bool,
    schema: PublicIntakeSchemaV1.fromJson(json['schema'] as String),
  );

  final PublicIntakeErrorCodeV1 code;

  final bool retryable;

  final PublicIntakeSchemaV1 schema;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'code': code.toJson(),
    'retryable': retryable,
    'schema': schema.toJson(),
  };
}
