// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/publisher-keys-v1.json

import 'common.dart';

/// The set of keys an org publishes with.
class PublisherKeySetV1 {
  const PublisherKeySetV1({
    required this.keys,
    required this.org,
    required this.schema,
  });

  factory PublisherKeySetV1.fromJson(Map<String, dynamic> json) => PublisherKeySetV1(
    keys: (json['keys'] as List<dynamic>).map((e) => PublisherKeyV1.fromJson(e as Map<String, dynamic>)).toList(),
    org: json['org'] as String,
    schema: json['schema'] as String,
  );

  final List<PublisherKeyV1> keys;

  final String org;

  final String schema;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'keys': keys.map((e) => e.toJson()).toList(),
    'org': org,
    'schema': schema,
  };
}
