// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/publish-response.json

class PublishResponse {
  const PublishResponse({
    required this.name,
    required this.org,
    required this.sha256,
    required this.version,
  });

  factory PublishResponse.fromJson(Map<String, dynamic> json) => PublishResponse(
    name: json['name'] as String,
    org: json['org'] as String,
    sha256: json['sha256'] as String,
    version: json['version'] as String,
  );

  final String name;

  final String org;

  final String sha256;

  final String version;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'name': name,
    'org': org,
    'sha256': sha256,
    'version': version,
  };
}
