// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/public-intake-accepted-v1.json

import 'common.dart';

enum PublicIntakeAcceptedStatusV1 {
  accepted('accepted');

  const PublicIntakeAcceptedStatusV1(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static PublicIntakeAcceptedStatusV1 fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown PublicIntakeAcceptedStatusV1: $value'),
  );

  static PublicIntakeAcceptedStatusV1? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}

/// A generic 202 response. It cannot disclose whether an email, organization, or
/// idempotency key was already known because none of those fields exist in the response
/// model.
class PublicIntakeAcceptedV1 {
  const PublicIntakeAcceptedV1({
    required this.schema,
    required this.status,
  });

  factory PublicIntakeAcceptedV1.fromJson(Map<String, dynamic> json) => PublicIntakeAcceptedV1(
    schema: PublicIntakeSchemaV1.fromJson(json['schema'] as String),
    status: PublicIntakeAcceptedStatusV1.fromJson(json['status'] as String),
  );

  final PublicIntakeSchemaV1 schema;

  final PublicIntakeAcceptedStatusV1 status;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'schema': schema.toJson(),
    'status': status.toJson(),
  };
}
