// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/quote-request-v1.json

import 'common.dart';

enum QuoteDeploymentModelV1 {
  evaluating('evaluating'),
  zedCloud('zed_cloud'),
  selfHosted('self_hosted'),
  hybrid('hybrid'),
  airGapped('air_gapped');

  const QuoteDeploymentModelV1(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static QuoteDeploymentModelV1 fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown QuoteDeploymentModelV1: $value'),
  );

  static QuoteDeploymentModelV1? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}

enum QuoteMigrationWindowV1 {
  exploring('exploring'),
  underThreeMonths('under_three_months'),
  threeToSixMonths('three_to_six_months'),
  sixToTwelveMonths('six_to_twelve_months'),
  overTwelveMonths('over_twelve_months');

  const QuoteMigrationWindowV1(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static QuoteMigrationWindowV1 fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown QuoteMigrationWindowV1: $value'),
  );

  static QuoteMigrationWindowV1? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}

enum QuoteMonthlyDownloadBandV1 {
  underOneHundredThousand('under_one_hundred_thousand'),
  oneHundredThousandToOneMillion('one_hundred_thousand_to_one_million'),
  oneMillionToTenMillion('one_million_to_ten_million'),
  overTenMillion('over_ten_million'),
  unknown('unknown');

  const QuoteMonthlyDownloadBandV1(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static QuoteMonthlyDownloadBandV1 fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown QuoteMonthlyDownloadBandV1: $value'),
  );

  static QuoteMonthlyDownloadBandV1? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}

enum QuotePackageCountBandV1 {
  underOneHundred('under_one_hundred'),
  oneHundredToOneThousand('one_hundred_to_one_thousand'),
  oneThousandToTenThousand('one_thousand_to_ten_thousand'),
  overTenThousand('over_ten_thousand'),
  unknown('unknown');

  const QuotePackageCountBandV1(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static QuotePackageCountBandV1 fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown QuotePackageCountBandV1: $value'),
  );

  static QuotePackageCountBandV1? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}

/// Request organization pricing. This stays a separate intent from pre-interest
/// registration, so registration can never silently become a quote request.
class QuoteRequestV1 {
  const QuoteRequestV1({
    required this.consentRevision,
    required this.consentedAt,
    required this.contactConsent,
    required this.contactName,
    required this.deploymentModel,
    required this.email,
    required this.interests,
    this.locale,
    required this.marketingConsent,
    this.marketingConsentRevision,
    required this.migrationWindow,
    required this.monthlyDownloads,
    required this.organizationName,
    required this.packageCount,
    this.referralCode,
    required this.requestId,
    this.requirementsSummary,
    this.role,
    required this.schema,
    required this.sourceHost,
    required this.teamSize,
    this.websiteUrl,
  });

  factory QuoteRequestV1.fromJson(Map<String, dynamic> json) => QuoteRequestV1(
    consentRevision: json['consentRevision'] as String,
    consentedAt: json['consentedAt'] as String,
    contactConsent: json['contactConsent'] as bool,
    contactName: json['contactName'] as String,
    deploymentModel: QuoteDeploymentModelV1.fromJson(json['deploymentModel'] as String),
    email: json['email'] as String,
    interests: (json['interests'] as List<dynamic>).map((e) => PublicIntakeInterestV1.fromJson(e as String)).toList(),
    locale: json['locale'] as String?,
    marketingConsent: json['marketingConsent'] as bool,
    marketingConsentRevision: json['marketingConsentRevision'] as String?,
    migrationWindow: QuoteMigrationWindowV1.fromJson(json['migrationWindow'] as String),
    monthlyDownloads: QuoteMonthlyDownloadBandV1.fromJson(json['monthlyDownloads'] as String),
    organizationName: json['organizationName'] as String,
    packageCount: QuotePackageCountBandV1.fromJson(json['packageCount'] as String),
    referralCode: json['referralCode'] as String?,
    requestId: json['requestId'] as String,
    requirementsSummary: json['requirementsSummary'] as String?,
    role: json['role'] as String?,
    schema: PublicIntakeSchemaV1.fromJson(json['schema'] as String),
    sourceHost: PublicIntakeSourceHostV1.fromJson(json['sourceHost'] as String),
    teamSize: QuoteTeamSizeBandV1.fromJson(json['teamSize'] as String),
    websiteUrl: json['websiteUrl'] as String?,
  );

  final String consentRevision;

  final String consentedAt;

  final bool contactConsent;

  final String contactName;

  final QuoteDeploymentModelV1 deploymentModel;

  final String email;

  final List<PublicIntakeInterestV1> interests;

  final String? locale;

  final bool marketingConsent;

  final String? marketingConsentRevision;

  final QuoteMigrationWindowV1 migrationWindow;

  final QuoteMonthlyDownloadBandV1 monthlyDownloads;

  final String organizationName;

  final QuotePackageCountBandV1 packageCount;

  final String? referralCode;

  final String requestId;

  /// Intentionally bounded and optional. The form warns submitters not to include
  /// credentials, private keys, tokens, or regulated data; the API must never log this field.
  final String? requirementsSummary;

  final String? role;

  final PublicIntakeSchemaV1 schema;

  final PublicIntakeSourceHostV1 sourceHost;

  final QuoteTeamSizeBandV1 teamSize;

  final String? websiteUrl;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'consentRevision': consentRevision,
    'consentedAt': consentedAt,
    'contactConsent': contactConsent,
    'contactName': contactName,
    'deploymentModel': deploymentModel.toJson(),
    'email': email,
    'interests': interests.map((e) => e.toJson()).toList(),
    'locale': locale,
    'marketingConsent': marketingConsent,
    'marketingConsentRevision': marketingConsentRevision,
    'migrationWindow': migrationWindow.toJson(),
    'monthlyDownloads': monthlyDownloads.toJson(),
    'organizationName': organizationName,
    'packageCount': packageCount.toJson(),
    'referralCode': referralCode,
    'requestId': requestId,
    'requirementsSummary': requirementsSummary,
    'role': role,
    'schema': schema.toJson(),
    'sourceHost': sourceHost.toJson(),
    'teamSize': teamSize.toJson(),
    'websiteUrl': websiteUrl,
  };
}

enum QuoteTeamSizeBandV1 {
  oneToTen('one_to_ten'),
  elevenToFifty('eleven_to_fifty'),
  fiftyOneToTwoHundred('fifty_one_to_two_hundred'),
  twoHundredOneToOneThousand('two_hundred_one_to_one_thousand'),
  overOneThousand('over_one_thousand'),
  unknown('unknown');

  const QuoteTeamSizeBandV1(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static QuoteTeamSizeBandV1 fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown QuoteTeamSizeBandV1: $value'),
  );

  static QuoteTeamSizeBandV1? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}
