// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/registry-namespace-claim-receipt.json

import 'common.dart';

/// Result observed after one provider-specific check or claim attempt.
enum RegistryNamespaceClaimOutcome {
  reserved('reserved'),
  existingOwnershipVerified('existing-ownership-verified'),
  firstPublicationCompleted('first-publication-completed'),
  unavailable('unavailable'),
  manualActionRequired('manual-action-required'),
  notReservable('not-reservable');

  const RegistryNamespaceClaimOutcome(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static RegistryNamespaceClaimOutcome fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown RegistryNamespaceClaimOutcome: $value'),
  );

  static RegistryNamespaceClaimOutcome? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}

/// Auditable observation for a single provider. A receipt can report unavailability, manual
/// work, or non-reservability; absence of a receipt is never interpreted as success.
class RegistryNamespaceClaimReceipt {
  const RegistryNamespaceClaimReceipt({
    this.coordinate,
    this.evidence,
    required this.observedAtUnixSeconds,
    required this.outcome,
    required this.planSha256,
    required this.provider,
    required this.schema,
    this.warnings,
  });

  factory RegistryNamespaceClaimReceipt.fromJson(Map<String, dynamic> json) => RegistryNamespaceClaimReceipt(
    coordinate: json['coordinate'] as String?,
    evidence: (json['evidence'] as List<dynamic>?)?.map((e) => RegistryNamespaceEvidence.fromJson(e as Map<String, dynamic>)).toList(),
    observedAtUnixSeconds: (json['observed_at_unix_seconds'] as num).toInt(),
    outcome: RegistryNamespaceClaimOutcome.fromJson(json['outcome'] as String),
    planSha256: json['plan_sha256'] as String,
    provider: RegistryNamespaceProvider.fromJson(json['provider'] as String),
    schema: json['schema'] as String,
    warnings: (json['warnings'] as List<dynamic>?)?.map((e) => e as String).toList(),
  );

  final String? coordinate;

  final List<RegistryNamespaceEvidence>? evidence;

  final int observedAtUnixSeconds;

  final RegistryNamespaceClaimOutcome outcome;

  /// Lowercase SHA-256 of `RegistryNamespacePlan::canonical_json_bytes()`.
  final String planSha256;

  final RegistryNamespaceProvider provider;

  final String schema;

  final List<String>? warnings;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'coordinate': coordinate,
    'evidence': evidence?.map((e) => e.toJson()).toList(),
    'observed_at_unix_seconds': observedAtUnixSeconds,
    'outcome': outcome.toJson(),
    'plan_sha256': planSha256,
    'provider': provider.toJson(),
    'schema': schema,
    'warnings': warnings,
  };
}

/// Non-secret evidence attached to a claim observation. `reference` is an opaque provider
/// reference or public URL; credentials and response bodies do not belong in receipts.
class RegistryNamespaceEvidence {
  const RegistryNamespaceEvidence({
    required this.kind,
    this.reference,
    this.sha256,
    required this.subject,
  });

  factory RegistryNamespaceEvidence.fromJson(Map<String, dynamic> json) => RegistryNamespaceEvidence(
    kind: RegistryNamespaceProof.fromJson(json['kind'] as String),
    reference: json['reference'] as String?,
    sha256: json['sha256'] as String?,
    subject: json['subject'] as String,
  );

  final RegistryNamespaceProof kind;

  final String? reference;

  final String? sha256;

  final String subject;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'kind': kind.toJson(),
    'reference': reference,
    'sha256': sha256,
    'subject': subject,
  };
}
