// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/registry-namespace-plan.json

import 'common.dart';

/// Provider-neutral step in an ordered namespace claim plan.
enum RegistryNamespaceAction {
  checkAvailability('check-availability'),
  createOrganization('create-organization'),
  registerNamespace('register-namespace'),
  verifyDomain('verify-domain'),
  createPublisher('create-publisher'),
  publishFirstPackage('publish-first-package'),
  addOwnerTeam('add-owner-team'),
  createGroup('create-group'),
  createWorkspace('create-workspace'),
  recordOwnershipEvidence('record-ownership-evidence');

  const RegistryNamespaceAction(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static RegistryNamespaceAction fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown RegistryNamespaceAction: $value'),
  );

  static RegistryNamespaceAction? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}

/// How far an ordinary client can take the claim without pretending that a manual or
/// first-publication boundary is an API operation.
enum RegistryNamespaceAutomation {
  /// A human must use the provider's web or administration interface.
  manualWebFlow('manual-web-flow'),
  /// Proof is established separately, after which an adapter may use an API.
  proofThenApi('proof-then-api'),
  /// The identity is established only by publishing the first real package.
  firstPublication('first-publication'),
  /// The provider has no organization-level namespace to reserve.
  notReservable('not-reservable');

  const RegistryNamespaceAutomation(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static RegistryNamespaceAutomation fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown RegistryNamespaceAutomation: $value'),
  );

  static RegistryNamespaceAutomation? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}

/// Actionability of one provider entry before any external mutation occurs.
enum RegistryNamespaceDisposition {
  /// All planner inputs exist; the ordered claim steps may now be attempted.
  actionable('actionable'),
  /// One or more required identity proofs or inputs are absent.
  missingPrerequisite('missing-prerequisite'),
  /// The provider requires a human-owned web or administration flow.
  manualActionRequired('manual-action-required'),
  /// No organization-level reservation exists for this provider.
  notReservable('not-reservable');

  const RegistryNamespaceDisposition(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static RegistryNamespaceDisposition fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown RegistryNamespaceDisposition: $value'),
  );

  static RegistryNamespaceDisposition? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}

/// One provider-specific identity and its pre-mutation claim procedure.
class RegistryNamespaceEntry {
  const RegistryNamespaceEntry({
    required this.automation,
    this.coordinate,
    required this.disposition,
    required this.model,
    this.packagePrefix,
    this.proofs,
    required this.provider,
    required this.steps,
    this.warnings,
  });

  factory RegistryNamespaceEntry.fromJson(Map<String, dynamic> json) => RegistryNamespaceEntry(
    automation: RegistryNamespaceAutomation.fromJson(json['automation'] as String),
    coordinate: json['coordinate'] as String?,
    disposition: RegistryNamespaceDisposition.fromJson(json['disposition'] as String),
    model: RegistryNamespaceModel.fromJson(json['model'] as String),
    packagePrefix: json['package_prefix'] as String?,
    proofs: (json['proofs'] as List<dynamic>?)?.map((e) => RegistryNamespaceProof.fromJson(e as String)).toList(),
    provider: RegistryNamespaceProvider.fromJson(json['provider'] as String),
    steps: (json['steps'] as List<dynamic>).map((e) => RegistryNamespaceStep.fromJson(e as Map<String, dynamic>)).toList(),
    warnings: (json['warnings'] as List<dynamic>?)?.map((e) => e as String).toList(),
  );

  final RegistryNamespaceAutomation automation;

  /// Exact provider coordinate when one exists, such as `@acme`, `com.example`,
  /// `example.com`, or `acme`.
  final String? coordinate;

  final RegistryNamespaceDisposition disposition;

  final RegistryNamespaceModel model;

  /// Advisory prefix for global package-name registries. A prefix is not a reserved namespace
  /// and must never be represented as one.
  final String? packagePrefix;

  final List<RegistryNamespaceProof>? proofs;

  final RegistryNamespaceProvider provider;

  final List<RegistryNamespaceStep> steps;

  final List<String>? warnings;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'automation': automation.toJson(),
    'coordinate': coordinate,
    'disposition': disposition.toJson(),
    'model': model.toJson(),
    'package_prefix': packagePrefix,
    'proofs': proofs?.map((e) => e.toJson()).toList(),
    'provider': provider.toJson(),
    'steps': steps.map((e) => e.toJson()).toList(),
    'warnings': warnings,
  };
}

/// Identity primitive exposed by one provider.
enum RegistryNamespaceModel {
  /// A literal account-owned package scope, such as `@acme` on npm.
  literalOrganizationScope('literal-organization-scope'),
  /// A verified package-prefix namespace, usually a reverse-DNS groupId.
  verifiedGroupIdPrefix('verified-group-id-prefix'),
  /// Globally unique package names with no reservable organization scope.
  globalPackageNames('global-package-names'),
  /// A publisher identity proven through control of a domain.
  verifiedPublisherDomain('verified-publisher-domain'),
  /// A source-forge organization login.
  forgeOrganization('forge-organization'),
  /// A source-forge top-level group path.
  forgeGroup('forge-group'),
  /// A source-forge workspace identifier.
  forgeWorkspace('forge-workspace');

  const RegistryNamespaceModel(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static RegistryNamespaceModel fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown RegistryNamespaceModel: $value'),
  );

  static RegistryNamespaceModel? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}

/// Deterministic pre-mutation claim plan. It says what must be done; it never says an
/// external namespace was successfully created or reserved.
class RegistryNamespacePlan {
  const RegistryNamespacePlan({
    required this.entries,
    required this.request,
    required this.schema,
    this.warnings,
  });

  factory RegistryNamespacePlan.fromJson(Map<String, dynamic> json) => RegistryNamespacePlan(
    entries: (json['entries'] as List<dynamic>).map((e) => RegistryNamespaceEntry.fromJson(e as Map<String, dynamic>)).toList(),
    request: RegistryNamespaceRequest.fromJson(json['request'] as Map<String, dynamic>),
    schema: json['schema'] as String,
    warnings: (json['warnings'] as List<dynamic>?)?.map((e) => e as String).toList(),
  );

  final List<RegistryNamespaceEntry> entries;

  final RegistryNamespaceRequest request;

  final String schema;

  final List<String>? warnings;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'entries': entries.map((e) => e.toJson()).toList(),
    'request': request.toJson(),
    'schema': schema,
    'warnings': warnings,
  };
}

/// User-controlled inputs from which a deterministic plan is derived.
class RegistryNamespaceRequest {
  const RegistryNamespaceRequest({
    required this.brand,
    this.domain,
    this.githubOwner,
    required this.providers,
  });

  factory RegistryNamespaceRequest.fromJson(Map<String, dynamic> json) => RegistryNamespaceRequest(
    brand: json['brand'] as String,
    domain: json['domain'] as String?,
    githubOwner: json['github_owner'] as String?,
    providers: (json['providers'] as List<dynamic>).map((e) => RegistryNamespaceProvider.fromJson(e as String)).toList(),
  );

  /// Portable lowercase brand slug shared by providers that support it.
  final String brand;

  /// Canonical lowercase registrable domain without scheme, port, path, or trailing dot.
  /// Required for domain-derived Maven and pub.dev identities.
  final String? domain;

  /// Explicit GitHub owner used for `io.github.<owner>` fallback namespaces and ownership
  /// proof. It is never inferred from credentials.
  final String? githubOwner;

  /// Providers requested by the caller. A plan must contain exactly one entry for each
  /// provider and no unrequested entry.
  final List<RegistryNamespaceProvider> providers;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'brand': brand,
    'domain': domain,
    'github_owner': githubOwner,
    'providers': providers.map((e) => e.toJson()).toList(),
  };
}

/// One ordered claim step. `manual` describes the provider boundary, not a suggestion that
/// the action has happened.
class RegistryNamespaceStep {
  const RegistryNamespaceStep({
    required this.action,
    required this.manual,
    this.prerequisite,
    required this.summary,
  });

  factory RegistryNamespaceStep.fromJson(Map<String, dynamic> json) => RegistryNamespaceStep(
    action: RegistryNamespaceAction.fromJson(json['action'] as String),
    manual: json['manual'] as bool,
    prerequisite: json['prerequisite'] as String?,
    summary: json['summary'] as String,
  );

  final RegistryNamespaceAction action;

  final bool manual;

  final String? prerequisite;

  final String summary;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'action': action.toJson(),
    'manual': manual,
    'prerequisite': prerequisite,
    'summary': summary,
  };
}
