// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/search-response.json

import 'common.dart';

class SearchResponse {
  const SearchResponse({
    required this.items,
    required this.query,
  });

  factory SearchResponse.fromJson(Map<String, dynamic> json) => SearchResponse(
    items: (json['items'] as List<dynamic>).map((e) => PackageSummary.fromJson(e as Map<String, dynamic>)).toList(),
    query: json['query'] as String,
  );

  final List<PackageSummary> items;

  final String query;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'items': items.map((e) => e.toJson()).toList(),
    'query': query,
  };
}
