// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/semantic-search-request.json

/// Body of `POST /v1/search/semantic` (RAG). The caller computes the query embedding with
/// its model; the server ranks stored package embeddings from the SAME model by cosine
/// distance. Vectors up to 2050 dims are accepted and zero-padded server-side.
class SemanticSearchRequest {
  const SemanticSearchRequest({
    required this.embedding,
    this.limit = 20,
    required this.model,
    this.tags,
  });

  factory SemanticSearchRequest.fromJson(Map<String, dynamic> json) => SemanticSearchRequest(
    embedding: (json['embedding'] as List<dynamic>).map((e) => (e as num).toDouble()).toList(),
    limit: json['limit'] == null
        ? 20
        : (json['limit'] as num).toInt(),
    model: json['model'] as String,
    tags: (json['tags'] as List<dynamic>?)?.map((e) => e as String).toList(),
  );

  /// The query embedding (native width; padded to 2050 server-side).
  final List<double> embedding;

  final int limit;

  /// Embedding model id, e.g. `openai/text-embedding-3-small`. Only stored embeddings from
  /// this model are searched.
  final String model;

  /// Optional tag filter: results must carry all of these tags.
  final List<String>? tags;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'embedding': embedding,
    'limit': limit,
    'model': model,
    'tags': tags,
  };
}
