// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/signed-version-v1.json

import 'common.dart';

/// A version-metadata document as a mirror serves it.
class SignedVersionV1 {
  const SignedVersionV1({
    required this.payload,
    required this.schema,
    required this.signatures,
  });

  factory SignedVersionV1.fromJson(Map<String, dynamic> json) => SignedVersionV1(
    payload: VersionAttestationV1.fromJson(json['payload'] as Map<String, dynamic>),
    schema: json['schema'] as String,
    signatures: (json['signatures'] as List<dynamic>).map((e) => DetachedSignatureV1.fromJson(e as Map<String, dynamic>)).toList(),
  );

  final VersionAttestationV1 payload;

  final String schema;

  final List<DetachedSignatureV1> signatures;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'payload': payload.toJson(),
    'schema': schema,
    'signatures': signatures.map((e) => e.toJson()).toList(),
  };
}

/// What a publisher asserts about one published version. This is a superset of what a
/// lockfile pins, plus the mirror set — so a consumer that learned about this version from
/// a mirror learns where else to look from the same signed document, and an attacker who
/// controls one mirror cannot quietly delete the others from the list.
class VersionAttestationV1 {
  const VersionAttestationV1({
    required this.format,
    this.mirrors,
    required this.name,
    required this.org,
    required this.publishedAt,
    required this.sha256,
    required this.size,
    required this.vcsCommit,
    required this.vcsTag,
    required this.version,
  });

  factory VersionAttestationV1.fromJson(Map<String, dynamic> json) => VersionAttestationV1(
    format: ArtifactFormat.fromJson(json['format'] as String),
    mirrors: (json['mirrors'] as List<dynamic>?)?.map((e) => MirrorDescriptorV1.fromJson(e as Map<String, dynamic>)).toList(),
    name: json['name'] as String,
    org: json['org'] as String,
    publishedAt: json['published_at'] as String,
    sha256: json['sha256'] as String,
    size: (json['size'] as num).toInt(),
    vcsCommit: json['vcs_commit'] as String,
    vcsTag: json['vcs_tag'] as String,
    version: json['version'] as String,
  );

  final ArtifactFormat format;

  /// Where these bytes can be fetched, in try order.
  final List<MirrorDescriptorV1>? mirrors;

  final String name;

  final String org;

  /// RFC 3339 timestamp.
  final String publishedAt;

  final String sha256;

  final int size;

  final String vcsCommit;

  final String vcsTag;

  final String version;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'format': format.toJson(),
    'mirrors': mirrors?.map((e) => e.toJson()).toList(),
    'name': name,
    'org': org,
    'published_at': publishedAt,
    'sha256': sha256,
    'size': size,
    'vcs_commit': vcsCommit,
    'vcs_tag': vcsTag,
    'version': version,
  };
}
