// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/signed-index-v1.json

import 'common.dart';

/// What a publisher asserts about a package as a whole.
class IndexAttestationV1 {
  const IndexAttestationV1({
    required this.generatedAt,
    this.mirrors,
    required this.name,
    required this.org,
    required this.sequence,
    required this.versions,
  });

  factory IndexAttestationV1.fromJson(Map<String, dynamic> json) => IndexAttestationV1(
    generatedAt: json['generated_at'] as String,
    mirrors: (json['mirrors'] as List<dynamic>?)?.map((e) => MirrorDescriptorV1.fromJson(e as Map<String, dynamic>)).toList(),
    name: json['name'] as String,
    org: json['org'] as String,
    sequence: (json['sequence'] as num).toInt(),
    versions: (json['versions'] as List<dynamic>).map((e) => IndexEntryV1.fromJson(e as Map<String, dynamic>)).toList(),
  );

  /// RFC 3339 timestamp this index was generated.
  final String generatedAt;

  /// Where this package's artifacts can be fetched, in try order.
  final List<MirrorDescriptorV1>? mirrors;

  final String name;

  final String org;

  /// Monotonic counter, incremented on every publish. Without it, a mirror could serve a
  /// genuinely-signed but stale index forever and hide a security release. A client that has
  /// seen sequence `n` must refuse anything below it, which converts an undetectable rollback
  /// into a loud, attributable failure.
  final int sequence;

  /// Every published version, newest first.
  final List<IndexEntryV1> versions;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'generated_at': generatedAt,
    'mirrors': mirrors?.map((e) => e.toJson()).toList(),
    'name': name,
    'org': org,
    'sequence': sequence,
    'versions': versions.map((e) => e.toJson()).toList(),
  };
}

/// One entry in a signed package index.
class IndexEntryV1 {
  const IndexEntryV1({
    required this.format,
    required this.publishedAt,
    required this.sha256,
    required this.size,
    required this.vcsCommit,
    required this.vcsTag,
    required this.version,
    this.yanked = false,
  });

  factory IndexEntryV1.fromJson(Map<String, dynamic> json) => IndexEntryV1(
    format: ArtifactFormat.fromJson(json['format'] as String),
    publishedAt: json['published_at'] as String,
    sha256: json['sha256'] as String,
    size: (json['size'] as num).toInt(),
    vcsCommit: json['vcs_commit'] as String,
    vcsTag: json['vcs_tag'] as String,
    version: json['version'] as String,
    yanked: json['yanked'] == null
        ? false
        : json['yanked'] as bool,
  );

  final ArtifactFormat format;

  final String publishedAt;

  final String sha256;

  final int size;

  final String vcsCommit;

  final String vcsTag;

  final String version;

  final bool yanked;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'format': format.toJson(),
    'published_at': publishedAt,
    'sha256': sha256,
    'size': size,
    'vcs_commit': vcsCommit,
    'vcs_tag': vcsTag,
    'version': version,
    'yanked': yanked,
  };
}

/// A package index as a mirror serves it.
class SignedIndexV1 {
  const SignedIndexV1({
    required this.payload,
    required this.schema,
    required this.signatures,
  });

  factory SignedIndexV1.fromJson(Map<String, dynamic> json) => SignedIndexV1(
    payload: IndexAttestationV1.fromJson(json['payload'] as Map<String, dynamic>),
    schema: json['schema'] as String,
    signatures: (json['signatures'] as List<dynamic>).map((e) => DetachedSignatureV1.fromJson(e as Map<String, dynamic>)).toList(),
  );

  final IndexAttestationV1 payload;

  final String schema;

  final List<DetachedSignatureV1> signatures;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'payload': payload.toJson(),
    'schema': schema,
    'signatures': signatures.map((e) => e.toJson()).toList(),
  };
}
