// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/sync-change-event.json

/// Hybrid Logical Clock stamp — the reconciliation key. Total order: `wall_ms`, then
/// `counter`, then `actor`.
class Hlc {
  const Hlc({
    required this.actor,
    required this.counter,
    required this.wallMs,
  });

  factory Hlc.fromJson(Map<String, dynamic> json) => Hlc(
    actor: json['actor'] as String,
    counter: (json['counter'] as num).toInt(),
    wallMs: (json['wall_ms'] as num).toInt(),
  );

  final String actor;

  final int counter;

  final int wallMs;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'actor': actor,
    'counter': counter,
    'wall_ms': wallMs,
  };
}

/// The change envelope both transports decode to (mirrors zed-sync `ChangeEvent`).
/// `version` is the ONLY reconciliation key; `sync_sequence` is the catch-up cursor and
/// never feeds reconciliation.
class SyncChangeEvent {
  const SyncChangeEvent({
    required this.atMs,
    required this.id,
    required this.op,
    this.row,
    this.syncSequence,
    required this.table,
    required this.version,
    this.writeKey,
  });

  factory SyncChangeEvent.fromJson(Map<String, dynamic> json) => SyncChangeEvent(
    atMs: (json['at_ms'] as num).toInt(),
    id: json['id'] as String,
    op: SyncOp.fromJson(json['op'] as String),
    row: json['row'],
    syncSequence: (json['sync_sequence'] as num?)?.toInt(),
    table: json['table'] as String,
    version: Hlc.fromJson(json['version'] as Map<String, dynamic>),
    writeKey: json['write_key'] as String?,
  );

  final int atMs;

  final String id;

  final SyncOp op;

  final Object? row;

  final int? syncSequence;

  final String table;

  final Hlc version;

  final String? writeKey;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'at_ms': atMs,
    'id': id,
    'op': op.toJson(),
    'row': row,
    'sync_sequence': syncSequence,
    'table': table,
    'version': version.toJson(),
    'write_key': writeKey,
  };
}

enum SyncOp {
  upsert('upsert'),
  delete('delete');

  const SyncOp(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static SyncOp fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown SyncOp: $value'),
  );

  static SyncOp? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}
