// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/sync-error-policy.json

/// How write/flush errors are surfaced (mirrors zed-sync `ErrorPolicy`).
enum SyncErrorPolicy {
  throwOnly("throw_only"),
  emitOnly("emit_only"),
  throwAndEmit("throw_and_emit"),
  silent("silent");

  const SyncErrorPolicy(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  static SyncErrorPolicy fromJson(String value) => values.firstWhere(
        (candidate) => candidate.wire == value,
        orElse: () => throw FormatException('unknown SyncErrorPolicy: $value'),
      );

  String toJson() => wire;
}
