// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/version-metadata.json

import 'common.dart';

/// On-the-wire formats for published package artifacts.
enum ArtifactFormat {
  tarGz('tar.gz'),
  zip('zip');

  const ArtifactFormat(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static ArtifactFormat fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown ArtifactFormat: $value'),
  );

  static ArtifactFormat? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}

class DetachedSignatureV1 {
  const DetachedSignatureV1({
    required this.algorithm,
    required this.keyId,
    required this.signatureMultibase,
  });

  factory DetachedSignatureV1.fromJson(Map<String, dynamic> json) => DetachedSignatureV1(
    algorithm: json['algorithm'] as String,
    keyId: json['key_id'] as String,
    signatureMultibase: json['signature_multibase'] as String,
  );

  final String algorithm;

  final String keyId;

  final String signatureMultibase;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'algorithm': algorithm,
    'key_id': keyId,
    'signature_multibase': signatureMultibase,
  };
}

class VersionMetadata {
  const VersionMetadata({
    required this.downloadUrl,
    this.format = ArtifactFormat.tarGz,
    this.mirrors,
    required this.name,
    required this.org,
    required this.publishedAt,
    required this.sha256,
    this.signatures,
    required this.size,
    this.vcsCommit,
    required this.vcsTag,
    required this.version,
    this.yanked = false,
  });

  factory VersionMetadata.fromJson(Map<String, dynamic> json) => VersionMetadata(
    downloadUrl: json['download_url'] as String,
    format: json['format'] == null
        ? ArtifactFormat.tarGz
        : ArtifactFormat.fromJson(json['format'] as String),
    mirrors: (json['mirrors'] as List<dynamic>?)?.map((e) => MirrorDescriptorV1.fromJson(e as Map<String, dynamic>)).toList(),
    name: json['name'] as String,
    org: json['org'] as String,
    publishedAt: json['published_at'] as String,
    sha256: json['sha256'] as String,
    signatures: (json['signatures'] as List<dynamic>?)?.map((e) => DetachedSignatureV1.fromJson(e as Map<String, dynamic>)).toList(),
    size: (json['size'] as num).toInt(),
    vcsCommit: json['vcs_commit'] as String?,
    vcsTag: json['vcs_tag'] as String,
    version: json['version'] as String,
    yanked: json['yanked'] == null
        ? false
        : json['yanked'] as bool,
  );

  /// Absolute or registry-relative URL the artifact can be fetched from.
  final String downloadUrl;

  final ArtifactFormat format;

  /// Alternate fetch locations (public R2, GitHub Release) so a client that already has this
  /// metadata can retry without the registry host. Empty when the publisher did not advertise
  /// mirrors; clients still guess standard GitHub/R2 paths from `org`/`name`/`vcs_tag`.
  final List<MirrorDescriptorV1>? mirrors;

  final String name;

  final String org;

  /// RFC 3339 timestamp.
  final String publishedAt;

  final String sha256;

  /// Detached signatures over the version attestation. Empty when the publisher did not sign;
  /// frozen installs still work from the lock digest.
  final List<DetachedSignatureV1>? signatures;

  final int size;

  final String? vcsCommit;

  final String vcsTag;

  final String version;

  final bool yanked;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'download_url': downloadUrl,
    'format': format.toJson(),
    'mirrors': mirrors?.map((e) => e.toJson()).toList(),
    'name': name,
    'org': org,
    'published_at': publishedAt,
    'sha256': sha256,
    'signatures': signatures?.map((e) => e.toJson()).toList(),
    'size': size,
    'vcs_commit': vcsCommit,
    'vcs_tag': vcsTag,
    'version': version,
    'yanked': yanked,
  };
}
