// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/yank-request.json

/// Body for the yank route. `yanked: false` restores a yanked version.
class YankRequest {
  const YankRequest({
    required this.yanked,
  });

  factory YankRequest.fromJson(Map<String, dynamic> json) => YankRequest(
    yanked: json['yanked'] as bool,
  );

  final bool yanked;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'yanked': yanked,
  };
}
