// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/yank-response.json

class YankResponse {
  const YankResponse({
    required this.name,
    required this.org,
    required this.version,
    required this.yanked,
  });

  factory YankResponse.fromJson(Map<String, dynamic> json) => YankResponse(
    name: json['name'] as String,
    org: json['org'] as String,
    version: json['version'] as String,
    yanked: json['yanked'] as bool,
  );

  final String name;

  final String org;

  final String version;

  final bool yanked;

  Map<String, dynamic> toJson() => <String, dynamic>{
    'name': name,
    'org': org,
    'version': version,
    'yanked': yanked,
  };
}
