// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.

/// Front-end contract types for the zed-pkg registry, generated from the
/// JSON Schemas that `zed-interfaces` (Rust) is the source of truth for.
library zed_interfaces;

export 'api_error.dart';
export 'audit_integrity_response.dart';
export 'audit_log_response.dart';
export 'claim_org_request.dart';
export 'claim_org_response.dart';
export 'common.dart';
export 'package_list_response.dart';
export 'package_metadata.dart';
export 'publish_response.dart';
export 'search_response.dart';
export 'semantic_search_request.dart';
export 'semantic_search_response.dart';
export 'sync_change_event.dart';
export 'sync_conflict_resolution.dart';
export 'sync_error_policy.dart';
export 'sync_write_mode.dart';
export 'version_metadata.dart';
export 'yank_request.dart';
export 'yank_response.dart';
