#!/usr/bin/env node
// JSON Schema -> front-end language slices for zed-interfaces.
//
//   node codegen/generate.mjs          # write src/dart/** and src/ts/**
//   node codegen/generate.mjs --check  # fail if anything is out of date (CI)
//
// Direction of truth, which is the opposite of most codegen setups:
//
//   src/rust/*.rs  --(cargo run --example generate_schemas)-->  schemas/*.json
//   schemas/*.json --(this script)-->  src/dart/lib/*.dart, src/ts/*.ts
//
// So Rust is hand-written and Dart/TS are derived. Only the schemas marked
// front-end-facing in schemas/index.json are emitted: Dart and TS exist for
// browser and Flutter clients, and the toolchain formats (manifest, lockfile,
// environment plans) have no front-end consumer. Never hand-edit the output.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const schemaDir = path.join(root, "schemas");
const outDir = path.join(root, "src");

const INDEX_FILE = "index.json";
const KNOWN_TARGETS = ["dart", "ts"];
const DART_PACKAGE = "zed_interfaces";
const BANNER =
  "GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.\n" +
  "Regenerate with `npm run codegen` after changing the Rust types.";

export class GenError extends Error {}
const fail = (msg) => {
  throw new GenError(msg);
};

// --- naming ------------------------------------------------------------------

const oneLine = (s) => String(s ?? "").replace(/\s+/g, " ").trim();
// Splits on separators *and* camelCase humps, so `VersionScheme` becomes
// VERSION_SCHEME rather than VERSIONSCHEME.
const words = (s) =>
  String(s).replace(/([a-z0-9])([A-Z])/g, "$1 $2").split(/[^A-Za-z0-9]+/).filter(Boolean);
const pascal = (s) => words(s).map((w) => w[0].toUpperCase() + w.slice(1)).join("");
const camel = (s) => {
  const p = pascal(s);
  return p ? p[0].toLowerCase() + p.slice(1) : p;
};
const snake = (s) => words(s).join("_").toLowerCase();

// Reserved words that cannot be identifiers at all.
const DART_KEYWORDS = new Set([
  "abstract", "as", "assert", "async", "await", "break", "case", "catch", "class", "const",
  "continue", "covariant", "default", "deferred", "do", "dynamic", "else", "enum", "export",
  "extends", "extension", "external", "factory", "false", "final", "finally", "for", "function",
  "get", "hide", "if", "implements", "import", "in", "interface", "is", "late", "library", "mixin",
  "new", "null", "on", "operator", "part", "required", "rethrow", "return", "sealed", "set",
  "show", "static", "super", "switch", "sync", "this", "throw", "true", "try", "typedef", "var",
  "void", "when", "while", "with", "yield",
]);
// Members every Object already has, plus the ones this generator adds. A field
// named `hashCode` or `toJson` would not compile.
const DART_CLASS_MEMBERS = new Set([
  "hashCode", "runtimeType", "toString", "noSuchMethod", "fromJson", "toJson",
]);
// Enums carry more: `name`, `index` and `values` are real members there, so an
// enum value called `name` collides even though a *field* called `name` is fine.
const DART_ENUM_MEMBERS = new Set([
  ...DART_CLASS_MEMBERS, "index", "values", "name", "compareTo", "wire",
]);
const dartIdent = (raw, reserved = DART_CLASS_MEMBERS) => {
  let id = camel(raw);
  if (!id) fail(`cannot derive a Dart identifier from ${JSON.stringify(raw)}`);
  if (/^[0-9]/.test(id)) id = `v${id}`;
  return DART_KEYWORDS.has(id) || reserved.has(id) ? `${id}_` : id;
};
const dartEnumIdent = (raw) => dartIdent(raw, DART_ENUM_MEMBERS);
// Types exported by dart:core. dart:core is imported implicitly, and an
// explicit import *wins* over it — so a generated class named `Duration` would
// not raise an ambiguity error, it would silently shadow the real one and
// break unrelated consumer code with a baffling message. Fail at generation
// time instead. (zed-lib shipped exactly this bug with a `Comparator` class.)
const DART_CORE_TYPES = new Set([
  "BigInt", "Comparable", "Comparator", "DateTime", "Deprecated", "Duration", "Enum", "Error",
  "Exception", "Expando", "Function", "Future", "Invocation", "Iterable", "Iterator", "List",
  "Map", "MapEntry", "Match", "Null", "Object", "Pattern", "Record", "RegExp", "RegExpMatch",
  "Rune", "Runes", "Set", "Sink", "StackTrace", "Stopwatch", "Stream", "String", "StringBuffer",
  "StringSink", "Symbol", "Type", "Uri", "UriData", "WeakReference",
]);
// Dart's own lints prefer single quotes; `$` starts an interpolation, so it
// has to be escaped even inside a plain literal.
const dartStr = (value) =>
  `'${String(value).replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\$/g, "\\$").replace(/\n/g, "\\n")}'`;
// TS keeps wire keys verbatim so a decoded response is the interface; only
// non-identifier keys need quoting.
const TS_IDENT_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const tsKey = (wire) => (TS_IDENT_RE.test(wire) ? wire : JSON.stringify(wire));

/**
 * Greedy word wrap. A word longer than `width` gets its own over-long line
 * rather than being dropped: this used to be a regex that silently discarded
 * everything before the last fitting chunk, which lost 112 of 200 characters
 * on a description with no spaces.
 */
function wrap(text, width) {
  const lines = [];
  let line = "";
  for (const word of text.split(" ")) {
    if (!word) continue;
    if (!line) line = word;
    else if (line.length + 1 + word.length <= width) line += ` ${word}`;
    else {
      lines.push(line);
      line = word;
    }
  }
  if (line) lines.push(line);
  return lines;
}

// Doc-comment escapers: a description can never break out of the comment.
const dartDoc = (s, indent = "") => {
  const text = oneLine(s);
  if (!text) return "";
  return `${wrap(text, 88).map((line) => `${indent}/// ${line}`).join("\n")}\n`;
};
const tsDoc = (s, indent = "") => {
  const text = oneLine(s).replace(/\*\//g, "*\\/");
  if (!text) return "";
  return `${indent}/** ${text} */\n`;
};

// --- schema -> IR ------------------------------------------------------------

const refName = (schema) =>
  schema && typeof schema.$ref === "string" ? schema.$ref.split("/").pop() : null;

/** Split `["string","null"]` / `anyOf:[T,{type:"null"}]` into (type, nullable). */
function splitNullable(schema, where) {
  if (Array.isArray(schema.anyOf)) {
    const variants = schema.anyOf;
    const nonNull = variants.filter((v) => !(v && v.type === "null"));
    if (nonNull.length !== variants.length - 1 || nonNull.length !== 1) {
      fail(`${where}: only \`anyOf: [T, {"type":"null"}]\` is supported, got ${variants.length} variants`);
    }
    return { schema: { ...nonNull[0] }, nullable: true };
  }
  if (Array.isArray(schema.type)) {
    const rest = schema.type.filter((t) => t !== "null");
    if (rest.length !== 1) {
      fail(`${where}: only one concrete type plus "null" is supported, got ${JSON.stringify(schema.type)}`);
    }
    return { schema: { ...schema, type: rest[0] }, nullable: schema.type.includes("null") };
  }
  return { schema, nullable: false };
}

/** String enums arrive as `enum: [...]` or as a `oneOf` of `const` strings. */
function enumValues(schema) {
  if (schema.type === "string" && Array.isArray(schema.enum) && schema.enum.length) {
    return schema.enum.map((wire) => ({ wire, description: "" }));
  }
  if (Array.isArray(schema.oneOf) && schema.oneOf.length) {
    const values = schema.oneOf.map((v) =>
      v && v.type === "string" && typeof v.const === "string"
        ? { wire: v.const, description: v.description || "" }
        : null,
    );
    if (values.every(Boolean)) return values;
  }
  return null;
}

/**
 * Resolve a property schema to a type reference. `emit` registers synthesized
 * inline enums so a schema can never silently degrade to a bare string.
 */
function typeRef(schema, where, emit) {
  if (schema === true || schema === undefined || schema === null) return { kind: "any", nullable: true };
  if (schema === false) fail(`${where}: \`false\` schemas have no inhabitants`);
  if (typeof schema !== "object") fail(`${where}: expected a schema object`);

  const { schema: inner, nullable } = splitNullable(schema, where);

  const ref = refName(inner);
  if (ref) return { kind: "ref", name: ref, nullable };

  const values = enumValues(inner);
  if (values) {
    // Inline enum on a property: give it a deterministic name and hoist it.
    const name = emit ? emit(values, inner.description || "") : null;
    if (!name) fail(`${where}: inline enums are only supported on object properties`);
    return { kind: "ref", name, nullable };
  }

  switch (inner.type) {
    case "string":
      return { kind: "string", nullable };
    case "integer":
      return { kind: "int", nullable };
    case "number":
      return { kind: "double", nullable };
    case "boolean":
      return { kind: "bool", nullable };
    case "array":
      return { kind: "list", item: typeRef(inner.items, `${where}[]`, null), nullable };
    case "object": {
      if (inner.properties) fail(`${where}: inline object types are not supported — give it a $def`);
      return { kind: "map", value: typeRef(inner.additionalProperties, `${where}{}`, null), nullable };
    }
    case undefined:
      return { kind: "any", nullable: true };
    default:
      fail(`${where}: unsupported JSON Schema type ${JSON.stringify(inner.type)}`);
  }
}

/** One named type: a class or an enum. */
function buildType(name, schema, sourceFile, sink) {
  if (!/^[A-Z][A-Za-z0-9]*$/.test(name)) {
    fail(`${sourceFile}: type name \`${name}\` must be PascalCase — it becomes a class in three languages`);
  }
  if (DART_CORE_TYPES.has(name)) {
    fail(
      `${sourceFile}: type name \`${name}\` collides with dart:core's \`${name}\`, which it would ` +
        `silently shadow in every consumer — rename the Rust type`,
    );
  }
  const values = enumValues(schema);
  if (values) {
    return { kind: "enum", name, description: schema.description || "", values, sourceFile };
  }
  if (schema.type !== "object" && schema.properties === undefined) {
    fail(`${sourceFile}:${name}: only object and string-enum types can be generated`);
  }
  const required = new Set(schema.required || []);
  const props = Object.entries(schema.properties || {}).map(([wire, propSchema]) => {
    const where = `${sourceFile}:${name}.${wire}`;
    const emitInline = (values_, description) => {
      const inlineName = `${name}${pascal(wire)}`;
      sink.push({ kind: "enum", name: inlineName, description, values: values_, sourceFile });
      return inlineName;
    };
    const type = typeRef(propSchema, where, emitInline);
    const hasDefault = propSchema && typeof propSchema === "object" && "default" in propSchema;
    return {
      wire,
      dart: dartIdent(wire),
      type,
      required: required.has(wire),
      // A serde default means the field is optional on the wire but always
      // meaningful, so Dart keeps it non-nullable and falls back to the default.
      default: hasDefault ? propSchema.default : undefined,
      hasDefault,
      description: (propSchema && propSchema.description) || "",
    };
  });
  return { kind: "object", name, description: schema.description || "", props, sourceFile };
}

// --- load + validate ---------------------------------------------------------

export function loadIndex(dir = schemaDir) {
  const indexPath = path.join(dir, INDEX_FILE);
  if (!fs.existsSync(indexPath)) fail(`missing schemas/${INDEX_FILE}`);
  let index;
  try {
    index = JSON.parse(fs.readFileSync(indexPath, "utf8"));
  } catch (error) {
    fail(`schemas/${INDEX_FILE} is not valid JSON: ${error.message}`);
  }
  if (!Array.isArray(index.schemas)) fail(`schemas/${INDEX_FILE} must have a \`schemas\` array`);

  const listed = new Map();
  for (const entry of index.schemas) {
    if (!entry || typeof entry.file !== "string") fail(`schemas/${INDEX_FILE}: every entry needs a \`file\``);
    // The file name becomes an output path under src/, so it may not escape
    // the schema directory. `manifest.rs` applies the same rule to target
    // dirs; codegen should not be the looser of the two.
    if (!/^[a-z0-9][a-z0-9-]*\.json$/.test(entry.file)) {
      fail(
        `schemas/${INDEX_FILE}: \`${entry.file}\` must be a kebab-case *.json file name in this directory`,
      );
    }
    if (listed.has(entry.file)) fail(`schemas/${INDEX_FILE}: ${entry.file} is listed twice`);
    if (!Array.isArray(entry.targets)) fail(`schemas/${INDEX_FILE}: ${entry.file} needs a \`targets\` array`);
    for (const target of entry.targets) {
      if (!KNOWN_TARGETS.includes(target)) {
        fail(`schemas/${INDEX_FILE}: ${entry.file} requests unknown target ${JSON.stringify(target)}`);
      }
    }
    if (!fs.existsSync(path.join(dir, entry.file))) {
      fail(`schemas/${INDEX_FILE} lists ${entry.file}, which does not exist`);
    }
    listed.set(entry.file, entry);
  }

  // A new schema must be classified, not silently skipped: that is the whole
  // point of the index, so an unlisted file is an error rather than a default.
  const onDisk = fs.readdirSync(dir).filter((f) => f.endsWith(".json") && f !== INDEX_FILE);
  const missing = onDisk.filter((f) => !listed.has(f));
  if (missing.length) {
    fail(
      `schemas/${INDEX_FILE} does not classify: ${missing.join(", ")}\n` +
        `  add each file with "targets": ["dart","ts"] (front-end-facing) or "targets": [] (Rust-only)`,
    );
  }
  return [...listed.values()];
}

/**
 * Build the emit plan: every generated type, assigned to a module. A type used
 * by two schemas is hoisted into `common` so neither slice defines it twice.
 */
export function plan() {
  const entries = loadIndex().filter((entry) => entry.targets.length > 0);
  const modules = new Map(); // module name -> { title, types[] }
  const byName = new Map(); // type name -> { type, modules:Set }

  for (const entry of entries) {
    const moduleName = entry.file.replace(/\.json$/, "");
    let doc;
    try {
      doc = JSON.parse(fs.readFileSync(path.join(schemaDir, entry.file), "utf8"));
    } catch (error) {
      fail(`${entry.file} is not valid JSON: ${error.message}`);
    }
    if (typeof doc.title !== "string" || !/^[A-Z][A-Za-z0-9]*$/.test(doc.title)) {
      fail(`${entry.file}: needs a PascalCase \`title\` (it names the generated type)`);
    }

    const collected = [];
    for (const [name, def] of Object.entries(doc.$defs || {})) {
      collected.push(buildType(name, def, entry.file, collected));
    }
    collected.push(buildType(doc.title, doc, entry.file, collected));

    modules.set(moduleName, { file: entry.file, targets: entry.targets, types: [], root: doc.title });
    for (const type of collected) {
      const seen = byName.get(type.name);
      if (seen) {
        // Same name from two schemas is fine when the shape matches (schemars
        // re-emits a shared Rust type into each schema); a mismatch is a real
        // contract bug and must not be papered over by picking one.
        if (JSON.stringify(stable(type)) !== JSON.stringify(stable(seen.type))) {
          fail(
            `type \`${type.name}\` is defined differently in ${seen.type.sourceFile} and ${type.sourceFile}`,
          );
        }
        seen.modules.add(moduleName);
      } else {
        byName.set(type.name, { type, modules: new Set([moduleName]) });
      }
    }
  }

  const home = new Map(); // type name -> module that defines it
  for (const [name, { type, modules: owners }] of byName) {
    home.set(name, owners.size > 1 ? "common" : [...owners][0]);
    void type;
  }
  if ([...home.values()].includes("common")) {
    modules.set("common", { file: null, targets: KNOWN_TARGETS, types: [], root: null });
  }
  for (const [name, { type }] of byName) modules.get(home.get(name)).types.push(type);

  for (const module of modules.values()) {
    module.types.sort((a, b) => a.name.localeCompare(b.name));
  }
  // Deterministic module order so the barrels never churn.
  const ordered = [...modules.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  return { modules: new Map(ordered), home, byName };
}

const stable = (value) => {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === "object") {
    const out = {};
    for (const key of Object.keys(value).sort()) {
      if (key === "sourceFile") continue;
      out[key] = stable(value[key]);
    }
    return out;
  }
  return value;
};

// --- Dart emitter ------------------------------------------------------------

const dartFileName = (module) => `${snake(module)}.dart`;

function dartType(ref, kinds) {
  const q = ref.nullable ? "?" : "";
  switch (ref.kind) {
    case "string": return `String${q}`;
    case "int": return `int${q}`;
    case "double": return `double${q}`;
    case "bool": return `bool${q}`;
    case "any": return "Object?";
    case "ref": return `${ref.name}${q}`;
    case "list": return `List<${dartType({ ...ref.item, nullable: ref.item.nullable }, kinds)}>${q}`;
    case "map": return `Map<String, ${dartType(ref.value, kinds)}>${q}`;
    default: return fail(`unsupported type ${ref.kind}`);
  }
}

/**
 * Expression decoding `expr` (a `dynamic`) into the Dart type of `ref`.
 * `nullable` emits null-aware access rather than a `== null ? null : …`
 * ternary, so the output reads like hand-written Dart.
 */
function dartDecode(ref, expr, kinds, nullable = false) {
  const q = nullable ? "?" : "";
  switch (ref.kind) {
    case "string": return `${expr} as String${q}`;
    case "int": return `(${expr} as num${q})${q}.toInt()`;
    case "double": return `(${expr} as num${q})${q}.toDouble()`;
    case "bool": return `${expr} as bool${q}`;
    case "any": return expr;
    case "ref":
      if (kinds.get(ref.name) === "enum") {
        return nullable
          ? `${ref.name}.maybeFromJson(${expr} as String?)`
          : `${ref.name}.fromJson(${expr} as String)`;
      }
      return nullable
        ? `${expr} == null ? null : ${ref.name}.fromJson(${expr} as Map<String, dynamic>)`
        : `${ref.name}.fromJson(${expr} as Map<String, dynamic>)`;
    case "list":
      return `(${expr} as List<dynamic>${q})${q}.map((e) => ${dartDecode(ref.item, "e", kinds, ref.item.nullable)}).toList()`;
    case "map":
      return `(${expr} as Map<String, dynamic>${q})${q}.map((k, v) => MapEntry(k, ${dartDecode(ref.value, "v", kinds, ref.value.nullable)}))`;
    default: return fail(`unsupported type ${ref.kind}`);
  }
}

/** Expression encoding the Dart field `name` back to JSON. */
function dartEncode(ref, name, kinds) {
  const q = ref.nullable ? "?" : "";
  switch (ref.kind) {
    case "ref":
      // Both classes and enums expose `toJson()`, so the call is the same.
      return `${name}${q}.toJson()`;
    case "list": {
      const inner = dartEncode(ref.item, "e", kinds);
      return inner === "e" ? name : `${name}${q}.map((e) => ${inner}).toList()`;
    }
    case "map": {
      const inner = dartEncode(ref.value, "v", kinds);
      return inner === "v" ? name : `${name}${q}.map((k, v) => MapEntry(k, ${inner}))`;
    }
    default:
      return name;
  }
}

function dartLiteral(ref, value, kinds) {
  if (value === null || value === undefined) return "null";
  if (ref.kind === "ref" && kinds.get(ref.name) === "enum") {
    return `${ref.name}.${dartEnumIdent(String(value))}`;
  }
  if (ref.kind === "list") return "const []";
  if (ref.kind === "map") return "const {}";
  if (typeof value === "string") return dartStr(value);
  if (typeof value === "boolean" || typeof value === "number") return String(value);
  return fail(`unsupported default ${JSON.stringify(value)}`);
}

function dartEnum(type) {
  const members = type.values.map((v) => ({ ...v, dart: dartEnumIdent(v.wire) }));
  const seen = new Set();
  for (const m of members) {
    if (seen.has(m.dart)) fail(`enum ${type.name}: values ${m.wire} collide on Dart name ${m.dart}`);
    seen.add(m.dart);
  }
  const body = members
    .map((m, i) => `${dartDoc(m.description, "  ")}  ${m.dart}(${dartStr(m.wire)})${i === members.length - 1 ? ";" : ","}`)
    .join("\n");
  return `${dartDoc(type.description)}enum ${type.name} {
${body}

  const ${type.name}(this.wire);

  /// The value as it appears in JSON.
  final String wire;

  /// Throws [FormatException] on a value this build does not know — an
  /// unrecognized variant is a version skew, not something to decode past.
  static ${type.name} fromJson(String value) => values.firstWhere(
    (candidate) => candidate.wire == value,
    orElse: () => throw FormatException('unknown ${type.name}: $value'),
  );

  static ${type.name}? maybeFromJson(String? value) =>
      value == null ? null : fromJson(value);

  String toJson() => wire;
}`;
}

/** How a property is modelled in Dart: nullable unless required or defaulted. */
function dartFieldRef(prop) {
  if (prop.type.kind === "any") return { ...prop.type, nullable: true };
  // A non-required field with a serde default is still always meaningful — the
  // default fills in — so it stays non-nullable.
  const nullable = prop.type.nullable || (!prop.required && !prop.hasDefault);
  return { ...prop.type, nullable };
}

function dartClass(type, kinds) {
  const ctorParams = type.props
    .map((p) => {
      const ref = dartFieldRef(p);
      if (!ref.nullable && p.hasDefault && !p.required) {
        return `    this.${p.dart} = ${dartLiteral(p.type, p.default, kinds)},`;
      }
      return ref.nullable ? `    this.${p.dart},` : `    required this.${p.dart},`;
    })
    .join("\n");

  const decode = type.props
    .map((p) => {
      const ref = dartFieldRef(p);
      const raw = `json[${dartStr(p.wire)}]`;
      if (p.type.kind === "any") return `    ${p.dart}: ${raw},`;
      if (!ref.nullable && p.hasDefault && !p.required) {
        // Absent means "take the default", which is what the Rust side does.
        return `    ${p.dart}: ${raw} == null\n        ? ${dartLiteral(p.type, p.default, kinds)}\n        : ${dartDecode(p.type, raw, kinds)},`;
      }
      return `    ${p.dart}: ${dartDecode(p.type, raw, kinds, ref.nullable)},`;
    })
    .join("\n");

  const fields = type.props
    .map((p) => `${dartDoc(p.description, "  ")}  final ${dartType(dartFieldRef(p), kinds)} ${p.dart};`)
    .join("\n\n");

  // Every key is written, with an explicit null for absent optionals: serde
  // decodes null into None, so the round-trip back into Rust is lossless.
  const encode = type.props
    .map((p) => `    ${dartStr(p.wire)}: ${dartEncode(dartFieldRef(p), p.dart, kinds)},`)
    .join("\n");

  return `${dartDoc(type.description)}class ${type.name} {
  const ${type.name}({
${ctorParams}
  });

  factory ${type.name}.fromJson(Map<String, dynamic> json) => ${type.name}(
${decode}
  );

${fields}

  Map<String, dynamic> toJson() => <String, dynamic>{
${encode}
  };
}`;
}

function emitDart(built) {
  const { modules, home } = built;
  const kinds = new Map([...built.byName].map(([name, v]) => [name, v.type.kind]));
  const files = {};
  const libFiles = [];

  for (const [moduleName, module] of modules) {
    if (!module.targets.includes("dart")) continue;
    const imports = new Set();
    for (const type of module.types) {
      const refs = type.kind === "object" ? type.props.map((p) => p.type) : [];
      for (const ref of refs) collectRefs(ref).forEach((name) => {
        const owner = home.get(name);
        if (owner && owner !== moduleName) imports.add(dartFileName(owner));
      });
    }
    const header =
      BANNER.split("\n").map((line) => `// ${line}`).join("\n") +
      (module.file ? `\n// Source: schemas/${module.file}` : "\n// Source: types shared by more than one schema") +
      "\n";
    const importBlock = [...imports].sort().map((f) => `import '${f}';`).join("\n");
    const body = module.types
      .map((type) => (type.kind === "enum" ? dartEnum(type) : dartClass(type, kinds)))
      .join("\n\n");
    const file = dartFileName(moduleName);
    files[`dart/lib/${file}`] = `${header}${importBlock ? `\n${importBlock}\n` : ""}\n${body}\n`;
    libFiles.push(file);
  }

  const barrel =
    BANNER.split("\n").map((line) => `// ${line}`).join("\n") +
    `\n\n/// Front-end contract types for the zed-pkg registry, generated from the\n` +
    `/// JSON Schemas that \`zed-interfaces\` (Rust) is the source of truth for.\n` +
    `library ${DART_PACKAGE};\n\n` +
    libFiles.sort().map((f) => `export '${f}';`).join("\n") +
    "\n";
  files[`dart/lib/${DART_PACKAGE}.dart`] = barrel;
  return files;
}

function collectRefs(ref, acc = []) {
  if (!ref) return acc;
  if (ref.kind === "ref") acc.push(ref.name);
  if (ref.kind === "list") collectRefs(ref.item, acc);
  if (ref.kind === "map") collectRefs(ref.value, acc);
  return acc;
}

// --- TypeScript emitter ------------------------------------------------------

function tsType(ref, kinds) {
  const base = (() => {
    switch (ref.kind) {
      case "string": return "string";
      case "int": return "number";
      case "double": return "number";
      case "bool": return "boolean";
      case "any": return "unknown";
      case "ref": return ref.name;
      case "list": return `readonly ${tsType(ref.item, kinds)}[]`;
      case "map": return `Readonly<Record<string, ${tsType(ref.value, kinds)}>>`;
      default: return fail(`unsupported type ${ref.kind}`);
    }
  })();
  // `unknown` already admits null; `unknown | null` is the same type written
  // twice, and tsc's own lint rules flag it.
  return ref.nullable && ref.kind !== "any" ? `${base} | null` : base;
}

function tsEnum(type) {
  const union = type.values.map((v) => JSON.stringify(v.wire)).join(" | ");
  const values = type.values.map((v) => JSON.stringify(v.wire)).join(", ");
  const docLines = type.values
    .filter((v) => v.description)
    .map((v) => ` * - \`${v.wire}\`: ${oneLine(v.description).replace(/\*\//g, "*\\/")}`)
    .join("\n");
  const doc = type.description || docLines
    ? `/**\n${oneLine(type.description) ? ` * ${oneLine(type.description).replace(/\*\//g, "*\\/")}\n` : ""}${docLines ? `${docLines}\n` : ""} */\n`
    : "";
  return `${doc}export type ${type.name} = ${union};

/** Every \`${type.name}\` value, in schema order — for validation and pickers. */
export const ${snake(type.name).toUpperCase()}_VALUES = [${values}] as const;`;
}

function tsInterface(type, kinds) {
  const fields = type.props
    .map((p) => {
      const optional = !p.required;
      return `${tsDoc(p.description, "  ")}  readonly ${tsKey(p.wire)}${optional ? "?" : ""}: ${tsType(p.type, kinds)};`;
    })
    .join("\n");
  return `${tsDoc(type.description)}export interface ${type.name} {
${fields}
}`;
}

function emitTs(built) {
  const { modules, home } = built;
  const kinds = new Map([...built.byName].map(([name, v]) => [name, v.type.kind]));
  const files = {};
  const moduleFiles = [];

  for (const [moduleName, module] of modules) {
    if (!module.targets.includes("ts")) continue;
    const imports = new Map(); // module -> Set(names)
    for (const type of module.types) {
      if (type.kind !== "object") continue;
      for (const prop of type.props) {
        for (const name of collectRefs(prop.type)) {
          const owner = home.get(name);
          if (owner && owner !== moduleName) {
            if (!imports.has(owner)) imports.set(owner, new Set());
            imports.get(owner).add(name);
          }
        }
      }
    }
    const header =
      BANNER.split("\n").map((line) => `// ${line}`).join("\n") +
      (module.file ? `\n// Source: schemas/${module.file}` : "\n// Source: types shared by more than one schema") +
      "\n";
    const importBlock = [...imports.entries()]
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map(([owner, names]) => `import type { ${[...names].sort().join(", ")} } from "./${owner}.ts";`)
      .join("\n");
    const body = module.types
      .map((type) => (type.kind === "enum" ? tsEnum(type) : tsInterface(type, kinds)))
      .join("\n\n");
    files[`ts/${moduleName}.ts`] = `${header}${importBlock ? `\n${importBlock}\n` : ""}\n${body}\n`;
    moduleFiles.push(moduleName);
  }

  files["ts/index.ts"] =
    BANNER.split("\n").map((line) => `// ${line}`).join("\n") +
    "\n\n" +
    moduleFiles.sort().map((m) => `export * from "./${m}.ts";`).join("\n") +
    "\n";
  return files;
}

// --- build + write -----------------------------------------------------------

export function build() {
  const built = plan();
  return { ...emitDart(built), ...emitTs(built) };
}

/** Exposed for codegen/generate.test.mjs — not part of any published surface. */
export const internals = {
  buildType, typeRef, emitDart, emitTs, dartIdent, dartEnumIdent, dartStr, snake, pascal,
};

/**
 * Generated files that are no longer produced must not linger — but the
 * cleanup may only touch files this generator wrote. Ownership is decided by
 * the banner, not by "it has the right extension and I don't recognize it":
 * the slice directories also hold hand-written files (tests, a tsconfig), and
 * an over-broad rule here deletes them.
 */
function staleFiles(expected) {
  const marker = BANNER.split("\n")[0];
  const stale = [];
  for (const dir of ["dart/lib", "ts"]) {
    const abs = path.join(outDir, dir);
    if (!fs.existsSync(abs)) continue;
    for (const name of fs.readdirSync(abs)) {
      const rel = `${dir}/${name}`;
      const full = path.join(abs, name);
      if (fs.statSync(full).isDirectory()) continue;
      if (!/\.(dart|ts)$/.test(name)) continue;
      if (rel in expected) continue;
      const head = fs.readFileSync(full, "utf8").slice(0, 200);
      if (head.includes(marker)) stale.push(rel);
    }
  }
  return stale;
}

function main() {
  const check = process.argv.includes("--check");
  let files;
  try {
    files = build();
  } catch (error) {
    console.error(`error: ${error instanceof Error ? error.message : String(error)}`);
    process.exit(2);
  }

  let drift = 0;
  for (const [rel, content] of Object.entries(files)) {
    const abs = path.join(outDir, rel);
    if (check) {
      const current = fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : null;
      if (current !== content) {
        console.error(`drift: src/${rel}`);
        if (process.env.GITHUB_ACTIONS === "true") {
          console.error(`::error file=src/${rel}::generated slice is out of date; run \`npm run codegen\``);
        }
        drift += 1;
      }
    } else {
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, content);
      console.log(`wrote src/${rel}`);
    }
  }

  for (const rel of staleFiles(files)) {
    if (check) {
      console.error(`stale: src/${rel} is no longer generated`);
      drift += 1;
    } else {
      fs.rmSync(path.join(outDir, rel));
      console.log(`removed src/${rel}`);
    }
  }

  if (check && drift > 0) {
    console.error(`${drift} file(s) out of date — run: npm run codegen`);
    process.exit(1);
  }
  if (check) console.log(`generated slices up to date (${Object.keys(files).length} files)`);
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) main();
