// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/api-error.json

/** Error body returned with any non-2xx status. */
export interface ApiError {
  /** Stable machine-readable code, e.g. `not_found`, `sha256_mismatch`, `tag_not_found`, `unauthorized`, `org_taken`. */
  readonly code: string;
  readonly message: string;
}
