// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/audit-integrity-response.json

/** The result of walking an org's audit chain end to end. */
export interface AuditIntegrityResponse {
  readonly entries_checked: number;
  /** The `seq` where verification first failed, if any. */
  readonly first_bad_seq?: number | null;
  /** The newest entry's hash — an anchor an operator can record externally so that later truncation of the whole tail is also detectable. */
  readonly head_hash?: string | null;
  /** True only when every entry's hash recomputes and every link matches. */
  readonly intact: boolean;
  readonly org: string;
  /** Machine-readable failure kind: `hash_mismatch` (an entry was edited), `broken_link` (an entry's `prev_hash` does not match its predecessor), or `sequence_gap` (an entry was deleted). */
  readonly problem?: string | null;
}
