// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/audit-log-response.json

/**
 * A state-changing action recorded in an org's audit log. Reads are never audited — only mutations of published state and of the namespace itself, so the log answers "who changed what" without drowning in traffic.
 * - `publish`: A version was published.
 * - `yank`: A version was yanked (hidden from fresh resolution).
 * - `unyank`: A previously yanked version was restored.
 * - `org_claim`: The org namespace was claimed.
 */
export type AuditAction = "publish" | "yank" | "unyank" | "org_claim";

/** Every `AuditAction` value, in schema order — for validation and pickers. */
export const AUDIT_ACTION_VALUES = ["publish", "yank", "unyank", "org_claim"] as const;

/** One audit-log record. The actor is identified by the *token* that acted — its name and role, never its secret — which is the identity a registry actually has (zed-docs issue #7 governance). */
export interface AuditEntry {
  /** Raw action string; `action_kind` is the parsed form when recognized. */
  readonly action: string;
  /** Parsed action, absent when this server build doesn't recognize it. */
  readonly action_kind?: AuditAction | null;
  /** The acting token's role (`owner`/`publisher`/`reader`, or `admin` for unscoped tokens). */
  readonly actor_role: string;
  /** Human-readable name of the token that acted. */
  readonly actor_token_name: string;
  /** RFC 3339 timestamp of the action. */
  readonly at: string;
  /** Extra context, e.g. the artifact sha256 for a publish. */
  readonly detail?: string | null;
  /** `sha256(audit_chain_preimage(..))` for this entry, lowercase hex. Empty from a pre-chain server. */
  readonly entry_hash?: string;
  /** The previous entry's `entry_hash`; `None` for the first entry in an org's chain. Linking each entry to its predecessor is what makes a silent deletion or edit detectable. */
  readonly prev_hash?: string | null;
  /** Position in the org's append-only chain, starting at 1. Gaps mean entries were deleted. Defaults to 0 when read from a server that predates the chain. */
  readonly seq?: number;
  /** What was acted on, e.g. `acme/http-kit@1.2.0` or the org slug. */
  readonly subject: string;
}

export interface AuditLogResponse {
  /** Most recent first. */
  readonly entries: readonly AuditEntry[];
  readonly org: string;
}
