// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/binary-artifact-list-v1.json

import type { BinaryArtifactMetadataV1 } from "./common.ts";

/** Collection response for every target/format artifact of one release. */
export interface BinaryArtifactListResponseV1 {
  /** Strictly sorted by `(platform.target, format)` with no duplicates. */
  readonly artifacts: readonly BinaryArtifactMetadataV1[];
  readonly name: string;
  readonly org: string;
  readonly schema: string;
  readonly version: string;
}
