// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/claim-org-response.json

export interface ClaimOrgResponse {
  /** False when the caller already owned the org. */
  readonly created: boolean;
  readonly slug: string;
}
