// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/claim-org-request.json

export interface ClaimOrgRequest {
  readonly slug: string;
}
