// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: types shared by more than one schema

export interface PackageSummary {
  readonly description?: string | null;
  readonly latest?: string | null;
  readonly name: string;
  readonly org: string;
  /** Free-form tags for filtering/discovery. */
  readonly tags?: readonly string[];
}
