// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/inspection-report.json

export interface InspectedLockedPackage {
  readonly materialized: boolean;
  readonly name: string;
  readonly org: string;
  readonly sha256: string;
  readonly store_present: boolean | null;
  readonly version: string;
}

export interface InspectedPackageIdentity {
  readonly name: string;
  readonly org: string;
  readonly version: string;
}

export interface InspectedPackageState {
  readonly identity: InspectedPackageIdentity | null;
  readonly lockfile: string;
  readonly manifest: string;
  readonly materialization_dir: string;
}

export type InspectionActionKind = "zed-command";

/** Every `InspectionActionKind` value, in schema order — for validation and pickers. */
export const INSPECTION_ACTION_KIND_VALUES = ["zed-command"] as const;

export interface InspectionAdapterOutput {
  readonly kind: string;
  readonly path: string;
  readonly present: boolean;
}

export interface InspectionCliIdentity {
  readonly command: string;
  readonly implementation: string;
  readonly loads_credentials: boolean;
  readonly mutates_project: boolean;
  readonly offline: boolean;
}

export interface InspectionDiagnostic {
  readonly actions?: readonly InspectionRecommendedAction[];
  readonly code: string;
  readonly detail?: string;
  readonly location: InspectionLocation;
  readonly message: string;
  readonly severity: InspectionSeverity;
}

export type InspectionHealth = "healthy" | "warning" | "error";

/** Every `InspectionHealth` value, in schema order — for validation and pickers. */
export const INSPECTION_HEALTH_VALUES = ["healthy", "warning", "error"] as const;

export interface InspectionLocation {
  readonly column?: number;
  readonly line?: number;
  readonly path: string;
}

export interface InspectionRecommendedAction {
  readonly argv: readonly string[];
  readonly cwd: string;
  readonly executes_package_code: boolean;
  readonly id: string;
  readonly kind: InspectionActionKind;
  readonly mutates_project: boolean;
  readonly requires_network: boolean;
  readonly title: string;
}

export interface InspectionReport {
  readonly adapter_outputs: readonly InspectionAdapterOutput[];
  readonly cli: InspectionCliIdentity;
  readonly diagnostics: readonly InspectionDiagnostic[];
  readonly interop: InteropInspection;
  readonly locked_packages: readonly InspectedLockedPackage[];
  readonly package: InspectedPackageState;
  readonly root: string;
  readonly schema_version: string;
  readonly summary: InspectionSummary;
  readonly workspace_members: readonly string[];
}

export type InspectionSeverity = "error" | "warning" | "info";

/** Every `InspectionSeverity` value, in schema order — for validation and pickers. */
export const INSPECTION_SEVERITY_VALUES = ["error", "warning", "info"] as const;

export interface InspectionSummary {
  readonly errors: number;
  readonly frozen_ready: boolean;
  readonly health: InspectionHealth;
  readonly recovery_pending: boolean;
  readonly warnings: number;
}

export interface InteropInspection {
  readonly git_submodules: InteropStatus;
  readonly mise: InteropStatus;
  readonly nix_develop: InteropStatus;
}

export interface InteropStatus {
  readonly declared: boolean;
  readonly detected: boolean;
  readonly source: string | null;
  readonly verified: boolean;
}
