// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/mirrors-response.json

import type { MirrorDescriptorV1 } from "./common.ts";

/** Response for `GET /v1/mirrors` and the well-known bootstrap path. */
export interface MirrorsResponse {
  readonly mirrors: readonly MirrorDescriptorV1[];
  readonly registry_url: string;
}
