// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/mirror-bootstrap-v1.json

import type { MirrorDescriptorV1 } from "./common.ts";

/** The document served at [`MIRROR_BOOTSTRAP_PATH`]. Deliberately small and unsigned-optional: its only job is to name hosts. A hostile bootstrap can send a client to a mirror of its choosing, and that mirror still cannot produce bytes matching the lockfile pin, nor metadata carrying a publisher signature it does not have. */
export interface MirrorBootstrapV1 {
  /** RFC 3339 timestamp this document was generated. */
  readonly generated_at: string;
  /** Every mirror the operator publishes, in try order. */
  readonly mirrors: readonly MirrorDescriptorV1[];
  /** Canonical registry base URL, for clients that recover mid-outage. */
  readonly registry_url: string;
  readonly schema: string;
}
