// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/org-keys-response.json

import type { PublisherKeyV1 } from "./common.ts";

/** Response for `GET /v1/orgs/{org}/keys`. */
export interface OrgKeysResponse {
  readonly keys: readonly PublisherKeyV1[];
  readonly org: string;
}
