// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/package-metadata.json

export interface PackageMetadata {
  readonly description?: string | null;
  readonly latest?: string | null;
  readonly name: string;
  readonly org: string;
  readonly repo_url: string;
  /** Free-form tags for filtering/discovery (multi-tag lookup). */
  readonly tags?: readonly string[];
  readonly vcs: Vcs;
  /** How this package's versions should be interpreted (semver by default). */
  readonly version_scheme?: VersionScheme;
  /** All published, non-yanked versions, newest first. */
  readonly versions: readonly string[];
}

/**
 * Version-control systems a package's source repository can live on. zed-pkg is VCS-agnostic by design: what gets installed is always a registry artifact, and the VCS is where provenance (tags) is anchored. Authors must create a matching tag on their declared backing repo (GitHub, GitLab, Bitbucket, Codeberg, SourceHut, Forgejo, Gitea, Azure DevOps, CodeCommit, Radicle, or self-hosted) before publishing. `jj` and Sapling are git-compatible and push to git remotes, so their provenance is verified through git tags.
 */
export type Vcs = "git" | "hg" | "jj" | "sapling" | "fossil" | "pijul";

/** Every `Vcs` value, in schema order — for validation and pickers. */
export const VCS_VALUES = ["git", "hg", "jj", "sapling", "fossil", "pijul"] as const;

/**
 * How a package's `version` string (and its published tags) should be interpreted. Defaults to [`VersionScheme::Semver`], which covers the vast majority of modern ecosystems.
 * - `semver`: Semantic Versioning. `package.version` must be valid semver; ranges (`^1.2`, `>=0.2 <0.5`) resolve to the max satisfying stable version.
 * - `calver`: Calendar Versioning (`2026.07.24`, `2026.07`). Normalized to a semver total order (leading zeros dropped, padded to major.minor.patch) so the same range algebra applies. See [`normalize_calver`].
 * - `opaque`: Arbitrary tags (`release-candidate-1`, `legacy-api`). No range algebra: a requirement must match a published version **exactly**.
 */
export type VersionScheme = "semver" | "calver" | "opaque";

/** Every `VersionScheme` value, in schema order — for validation and pickers. */
export const VERSION_SCHEME_VALUES = ["semver", "calver", "opaque"] as const;
