// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/package-list-response.json

import type { PackageSummary } from "./common.ts";

/** Response for `GET /v1/packages` (list all). */
export interface PackageListResponse {
  readonly items: readonly PackageSummary[];
  /** Total packages matching the filter (before limit/offset). */
  readonly total: number;
}
