// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/pre-interest-registration-request-v1.json

import type { PublicIntakeInterestV1, PublicIntakeSchemaV1, PublicIntakeSourceHostV1 } from "./common.ts";

/** Register interest without creating an account, quote, organization, or authenticated session. */
export interface PreInterestRegistrationRequestV1 {
  readonly consentRevision: string;
  /** RFC 3339 timestamp supplied by the browser and bounded by domain validation against server time. */
  readonly consentedAt: string;
  /** Must be true after validation. This is consent to store and contact, not account creation and not marketing consent. */
  readonly contactConsent: boolean;
  readonly contactName?: string | null;
  readonly email: string;
  readonly interests: readonly PublicIntakeInterestV1[];
  readonly locale?: string | null;
  readonly marketingConsent: boolean;
  readonly marketingConsentRevision?: string | null;
  readonly organizationName?: string | null;
  readonly partyType: PublicIntakePartyV1;
  readonly referralCode?: string | null;
  /** Client-generated UUID used together with `Idempotency-Key`. It is not returned from the public endpoint. */
  readonly requestId: string;
  readonly schema: PublicIntakeSchemaV1;
  readonly sourceHost: PublicIntakeSourceHostV1;
  readonly websiteUrl?: string | null;
}

export type PublicIntakePartyV1 = "individual" | "organization";

/** Every `PublicIntakePartyV1` value, in schema order — for validation and pickers. */
export const PUBLIC_INTAKE_PARTY_V1_VALUES = ["individual", "organization"] as const;
