// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/public-intake-accepted-v1.json

import type { PublicIntakeSchemaV1 } from "./common.ts";

export type PublicIntakeAcceptedStatusV1 = "accepted";

/** Every `PublicIntakeAcceptedStatusV1` value, in schema order — for validation and pickers. */
export const PUBLIC_INTAKE_ACCEPTED_STATUS_V1_VALUES = ["accepted"] as const;

/** A generic 202 response. It cannot disclose whether an email, organization, or idempotency key was already known because none of those fields exist in the response model. */
export interface PublicIntakeAcceptedV1 {
  readonly schema: PublicIntakeSchemaV1;
  readonly status: PublicIntakeAcceptedStatusV1;
}
