// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/publisher-keys-v1.json

import type { PublisherKeyV1 } from "./common.ts";

/** The set of keys an org publishes with. */
export interface PublisherKeySetV1 {
  readonly keys: readonly PublisherKeyV1[];
  readonly org: string;
  readonly schema: string;
}
