// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/public-intake-error-v1.json

import type { PublicIntakeSchemaV1 } from "./common.ts";

export type PublicIntakeErrorCodeV1 = "invalid_request" | "unsupported_media_type" | "payload_too_large" | "abuse_challenge_failed" | "rate_limited" | "temporarily_unavailable";

/** Every `PublicIntakeErrorCodeV1` value, in schema order — for validation and pickers. */
export const PUBLIC_INTAKE_ERROR_CODE_V1_VALUES = ["invalid_request", "unsupported_media_type", "payload_too_large", "abuse_challenge_failed", "rate_limited", "temporarily_unavailable"] as const;

/** Closed public error categories. No arbitrary detail or reflected input is present in the wire shape; operational detail belongs only in redacted internal telemetry keyed by a server-generated trace identifier. */
export interface PublicIntakeErrorV1 {
  readonly code: PublicIntakeErrorCodeV1;
  readonly retryable: boolean;
  readonly schema: PublicIntakeSchemaV1;
}
