// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/publish-response.json

export interface PublishResponse {
  readonly name: string;
  readonly org: string;
  readonly sha256: string;
  readonly version: string;
}
