// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/quote-request-v1.json

import type { PublicIntakeInterestV1, PublicIntakeSchemaV1, PublicIntakeSourceHostV1 } from "./common.ts";

export type QuoteDeploymentModelV1 = "evaluating" | "zed_cloud" | "self_hosted" | "hybrid" | "air_gapped";

/** Every `QuoteDeploymentModelV1` value, in schema order — for validation and pickers. */
export const QUOTE_DEPLOYMENT_MODEL_V1_VALUES = ["evaluating", "zed_cloud", "self_hosted", "hybrid", "air_gapped"] as const;

export type QuoteMigrationWindowV1 = "exploring" | "under_three_months" | "three_to_six_months" | "six_to_twelve_months" | "over_twelve_months";

/** Every `QuoteMigrationWindowV1` value, in schema order — for validation and pickers. */
export const QUOTE_MIGRATION_WINDOW_V1_VALUES = ["exploring", "under_three_months", "three_to_six_months", "six_to_twelve_months", "over_twelve_months"] as const;

export type QuoteMonthlyDownloadBandV1 = "under_one_hundred_thousand" | "one_hundred_thousand_to_one_million" | "one_million_to_ten_million" | "over_ten_million" | "unknown";

/** Every `QuoteMonthlyDownloadBandV1` value, in schema order — for validation and pickers. */
export const QUOTE_MONTHLY_DOWNLOAD_BAND_V1_VALUES = ["under_one_hundred_thousand", "one_hundred_thousand_to_one_million", "one_million_to_ten_million", "over_ten_million", "unknown"] as const;

export type QuotePackageCountBandV1 = "under_one_hundred" | "one_hundred_to_one_thousand" | "one_thousand_to_ten_thousand" | "over_ten_thousand" | "unknown";

/** Every `QuotePackageCountBandV1` value, in schema order — for validation and pickers. */
export const QUOTE_PACKAGE_COUNT_BAND_V1_VALUES = ["under_one_hundred", "one_hundred_to_one_thousand", "one_thousand_to_ten_thousand", "over_ten_thousand", "unknown"] as const;

/** Request organization pricing. This stays a separate intent from pre-interest registration, so registration can never silently become a quote request. */
export interface QuoteRequestV1 {
  readonly consentRevision: string;
  readonly consentedAt: string;
  readonly contactConsent: boolean;
  readonly contactName: string;
  readonly deploymentModel: QuoteDeploymentModelV1;
  readonly email: string;
  readonly interests: readonly PublicIntakeInterestV1[];
  readonly locale?: string | null;
  readonly marketingConsent: boolean;
  readonly marketingConsentRevision?: string | null;
  readonly migrationWindow: QuoteMigrationWindowV1;
  readonly monthlyDownloads: QuoteMonthlyDownloadBandV1;
  readonly organizationName: string;
  readonly packageCount: QuotePackageCountBandV1;
  readonly referralCode?: string | null;
  readonly requestId: string;
  /** Intentionally bounded and optional. The form warns submitters not to include credentials, private keys, tokens, or regulated data; the API must never log this field. */
  readonly requirementsSummary?: string | null;
  readonly role?: string | null;
  readonly schema: PublicIntakeSchemaV1;
  readonly sourceHost: PublicIntakeSourceHostV1;
  readonly teamSize: QuoteTeamSizeBandV1;
  readonly websiteUrl?: string | null;
}

export type QuoteTeamSizeBandV1 = "one_to_ten" | "eleven_to_fifty" | "fifty_one_to_two_hundred" | "two_hundred_one_to_one_thousand" | "over_one_thousand" | "unknown";

/** Every `QuoteTeamSizeBandV1` value, in schema order — for validation and pickers. */
export const QUOTE_TEAM_SIZE_BAND_V1_VALUES = ["one_to_ten", "eleven_to_fifty", "fifty_one_to_two_hundred", "two_hundred_one_to_one_thousand", "over_one_thousand", "unknown"] as const;
