// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/registry-namespace-plan.json

import type { RegistryNamespaceProof, RegistryNamespaceProvider } from "./common.ts";

/**
 * Provider-neutral step in an ordered namespace claim plan.
 */
export type RegistryNamespaceAction = "check-availability" | "create-organization" | "register-namespace" | "verify-domain" | "create-publisher" | "publish-first-package" | "add-owner-team" | "create-group" | "create-workspace" | "record-ownership-evidence";

/** Every `RegistryNamespaceAction` value, in schema order — for validation and pickers. */
export const REGISTRY_NAMESPACE_ACTION_VALUES = ["check-availability", "create-organization", "register-namespace", "verify-domain", "create-publisher", "publish-first-package", "add-owner-team", "create-group", "create-workspace", "record-ownership-evidence"] as const;

/**
 * How far an ordinary client can take the claim without pretending that a manual or first-publication boundary is an API operation.
 * - `manual-web-flow`: A human must use the provider's web or administration interface.
 * - `proof-then-api`: Proof is established separately, after which an adapter may use an API.
 * - `first-publication`: The identity is established only by publishing the first real package.
 * - `not-reservable`: The provider has no organization-level namespace to reserve.
 */
export type RegistryNamespaceAutomation = "manual-web-flow" | "proof-then-api" | "first-publication" | "not-reservable";

/** Every `RegistryNamespaceAutomation` value, in schema order — for validation and pickers. */
export const REGISTRY_NAMESPACE_AUTOMATION_VALUES = ["manual-web-flow", "proof-then-api", "first-publication", "not-reservable"] as const;

/**
 * Actionability of one provider entry before any external mutation occurs.
 * - `actionable`: All planner inputs exist; the ordered claim steps may now be attempted.
 * - `missing-prerequisite`: One or more required identity proofs or inputs are absent.
 * - `manual-action-required`: The provider requires a human-owned web or administration flow.
 * - `not-reservable`: No organization-level reservation exists for this provider.
 */
export type RegistryNamespaceDisposition = "actionable" | "missing-prerequisite" | "manual-action-required" | "not-reservable";

/** Every `RegistryNamespaceDisposition` value, in schema order — for validation and pickers. */
export const REGISTRY_NAMESPACE_DISPOSITION_VALUES = ["actionable", "missing-prerequisite", "manual-action-required", "not-reservable"] as const;

/** One provider-specific identity and its pre-mutation claim procedure. */
export interface RegistryNamespaceEntry {
  readonly automation: RegistryNamespaceAutomation;
  /** Exact provider coordinate when one exists, such as `@acme`, `com.example`, `example.com`, or `acme`. */
  readonly coordinate?: string | null;
  readonly disposition: RegistryNamespaceDisposition;
  readonly model: RegistryNamespaceModel;
  /** Advisory prefix for global package-name registries. A prefix is not a reserved namespace and must never be represented as one. */
  readonly package_prefix?: string | null;
  readonly proofs?: readonly RegistryNamespaceProof[];
  readonly provider: RegistryNamespaceProvider;
  readonly steps: readonly RegistryNamespaceStep[];
  readonly warnings?: readonly string[];
}

/**
 * Identity primitive exposed by one provider.
 * - `literal-organization-scope`: A literal account-owned package scope, such as `@acme` on npm.
 * - `verified-group-id-prefix`: A verified package-prefix namespace, usually a reverse-DNS groupId.
 * - `global-package-names`: Globally unique package names with no reservable organization scope.
 * - `verified-publisher-domain`: A publisher identity proven through control of a domain.
 * - `forge-organization`: A source-forge organization login.
 * - `forge-group`: A source-forge top-level group path.
 * - `forge-workspace`: A source-forge workspace identifier.
 */
export type RegistryNamespaceModel = "literal-organization-scope" | "verified-group-id-prefix" | "global-package-names" | "verified-publisher-domain" | "forge-organization" | "forge-group" | "forge-workspace";

/** Every `RegistryNamespaceModel` value, in schema order — for validation and pickers. */
export const REGISTRY_NAMESPACE_MODEL_VALUES = ["literal-organization-scope", "verified-group-id-prefix", "global-package-names", "verified-publisher-domain", "forge-organization", "forge-group", "forge-workspace"] as const;

/** Deterministic pre-mutation claim plan. It says what must be done; it never says an external namespace was successfully created or reserved. */
export interface RegistryNamespacePlan {
  readonly entries: readonly RegistryNamespaceEntry[];
  readonly request: RegistryNamespaceRequest;
  readonly schema: string;
  readonly warnings?: readonly string[];
}

/** User-controlled inputs from which a deterministic plan is derived. */
export interface RegistryNamespaceRequest {
  /** Portable lowercase brand slug shared by providers that support it. */
  readonly brand: string;
  /** Canonical lowercase registrable domain without scheme, port, path, or trailing dot. Required for domain-derived Maven and pub.dev identities. */
  readonly domain?: string | null;
  /** Explicit GitHub owner used for `io.github.<owner>` fallback namespaces and ownership proof. It is never inferred from credentials. */
  readonly github_owner?: string | null;
  /** Providers requested by the caller. A plan must contain exactly one entry for each provider and no unrequested entry. */
  readonly providers: readonly RegistryNamespaceProvider[];
}

/** One ordered claim step. `manual` describes the provider boundary, not a suggestion that the action has happened. */
export interface RegistryNamespaceStep {
  readonly action: RegistryNamespaceAction;
  readonly manual: boolean;
  readonly prerequisite?: string | null;
  readonly summary: string;
}
