// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/registry-namespace-claim-receipt.json

import type { RegistryNamespaceProof, RegistryNamespaceProvider } from "./common.ts";

/**
 * Result observed after one provider-specific check or claim attempt.
 */
export type RegistryNamespaceClaimOutcome = "reserved" | "existing-ownership-verified" | "first-publication-completed" | "unavailable" | "manual-action-required" | "not-reservable";

/** Every `RegistryNamespaceClaimOutcome` value, in schema order — for validation and pickers. */
export const REGISTRY_NAMESPACE_CLAIM_OUTCOME_VALUES = ["reserved", "existing-ownership-verified", "first-publication-completed", "unavailable", "manual-action-required", "not-reservable"] as const;

/** Auditable observation for a single provider. A receipt can report unavailability, manual work, or non-reservability; absence of a receipt is never interpreted as success. */
export interface RegistryNamespaceClaimReceipt {
  readonly coordinate?: string | null;
  readonly evidence?: readonly RegistryNamespaceEvidence[];
  readonly observed_at_unix_seconds: number;
  readonly outcome: RegistryNamespaceClaimOutcome;
  /** Lowercase SHA-256 of `RegistryNamespacePlan::canonical_json_bytes()`. */
  readonly plan_sha256: string;
  readonly provider: RegistryNamespaceProvider;
  readonly schema: string;
  readonly warnings?: readonly string[];
}

/** Non-secret evidence attached to a claim observation. `reference` is an opaque provider reference or public URL; credentials and response bodies do not belong in receipts. */
export interface RegistryNamespaceEvidence {
  readonly kind: RegistryNamespaceProof;
  readonly reference?: string | null;
  readonly sha256?: string | null;
  readonly subject: string;
}
