// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/search-response.json

import type { PackageSummary } from "./common";

export interface SearchResponse {
  readonly items: readonly PackageSummary[];
  readonly query: string;
}
