// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/semantic-search-response.json

export interface SemanticHit {
  readonly description?: string | null;
  /** Cosine distance (0 = identical direction, 2 = opposite). Lower is nearer. */
  readonly distance: number;
  readonly name: string;
  readonly org: string;
  readonly tags?: readonly string[];
}

export interface SemanticSearchResponse {
  readonly items: readonly SemanticHit[];
}
