// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/semantic-search-request.json

/** Body of `POST /v1/search/semantic` (RAG). The caller computes the query embedding with its model; the server ranks stored package embeddings from the SAME model by cosine distance. Vectors up to 2050 dims are accepted and zero-padded server-side. */
export interface SemanticSearchRequest {
  /** The query embedding (native width; padded to 2050 server-side). */
  readonly embedding: readonly number[];
  readonly limit?: number;
  /** Embedding model id, e.g. `openai/text-embedding-3-small`. Only stored embeddings from this model are searched. */
  readonly model: string;
  /** Optional tag filter: results must carry all of these tags. */
  readonly tags?: readonly string[];
}
