// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/signed-index-v1.json

import type { ArtifactFormat, DetachedSignatureV1, MirrorDescriptorV1 } from "./common.ts";

/** What a publisher asserts about a package as a whole. */
export interface IndexAttestationV1 {
  /** RFC 3339 timestamp this index was generated. */
  readonly generated_at: string;
  /** Where this package's artifacts can be fetched, in try order. */
  readonly mirrors?: readonly MirrorDescriptorV1[];
  readonly name: string;
  readonly org: string;
  /** Monotonic counter, incremented on every publish. Without it, a mirror could serve a genuinely-signed but stale index forever and hide a security release. A client that has seen sequence `n` must refuse anything below it, which converts an undetectable rollback into a loud, attributable failure. */
  readonly sequence: number;
  /** Every published version, newest first. */
  readonly versions: readonly IndexEntryV1[];
}

/** One entry in a signed package index. */
export interface IndexEntryV1 {
  readonly format: ArtifactFormat;
  readonly published_at: string;
  readonly sha256: string;
  readonly size: number;
  readonly vcs_commit: string;
  readonly vcs_tag: string;
  readonly version: string;
  readonly yanked?: boolean;
}

/** A package index as a mirror serves it. */
export interface SignedIndexV1 {
  readonly payload: IndexAttestationV1;
  readonly schema: string;
  readonly signatures: readonly DetachedSignatureV1[];
}
