// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/signed-version-v1.json

import type { ArtifactFormat, DetachedSignatureV1, MirrorDescriptorV1 } from "./common.ts";

/** A version-metadata document as a mirror serves it. */
export interface SignedVersionV1 {
  readonly payload: VersionAttestationV1;
  readonly schema: string;
  readonly signatures: readonly DetachedSignatureV1[];
}

/** What a publisher asserts about one published version. This is a superset of what a lockfile pins, plus the mirror set — so a consumer that learned about this version from a mirror learns where else to look from the same signed document, and an attacker who controls one mirror cannot quietly delete the others from the list. */
export interface VersionAttestationV1 {
  readonly format: ArtifactFormat;
  /** Where these bytes can be fetched, in try order. */
  readonly mirrors?: readonly MirrorDescriptorV1[];
  readonly name: string;
  readonly org: string;
  /** RFC 3339 timestamp. */
  readonly published_at: string;
  readonly sha256: string;
  readonly size: number;
  readonly vcs_commit: string;
  readonly vcs_tag: string;
  readonly version: string;
}
