// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/sync-error-policy.json

/**
 * How write/flush errors are surfaced (mirrors zed-sync `ErrorPolicy`).
 */
export type SyncErrorPolicy = "throw_only" | "emit_only" | "throw_and_emit" | "silent";

/** Every `SyncErrorPolicy` value, in schema order — for validation and pickers. */
export const SYNC_ERROR_POLICY_VALUES = ["throw_only", "emit_only", "throw_and_emit", "silent"] as const;
