// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/sync-write-mode.json

/**
 * Per-write optimism level (mirrors zed-sync `WriteMode`). Enum, not a boolean: a write names its exact behavior.
 */
export type SyncWriteMode = "local_only" | "optimistic_queue" | "optimistic_await_ack" | "server_first" | "server_only";

/** Every `SyncWriteMode` value, in schema order — for validation and pickers. */
export const SYNC_WRITE_MODE_VALUES = ["local_only", "optimistic_queue", "optimistic_await_ack", "server_first", "server_only"] as const;
