// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/sync-change-event.json

/** Hybrid Logical Clock stamp — the reconciliation key. Total order: `wall_ms`, then `counter`, then `actor`. */
export interface Hlc {
  readonly actor: string;
  readonly counter: number;
  readonly wall_ms: number;
}

/** The change envelope both transports decode to (mirrors zed-sync `ChangeEvent`). `version` is the ONLY reconciliation key; `sync_sequence` is the catch-up cursor and never feeds reconciliation. */
export interface SyncChangeEvent {
  readonly at_ms: number;
  readonly id: string;
  readonly op: SyncOp;
  readonly row?: unknown;
  readonly sync_sequence?: number | null;
  readonly table: string;
  readonly version: Hlc;
  readonly write_key?: string | null;
}

export type SyncOp = "upsert" | "delete";

/** Every `SyncOp` value, in schema order — for validation and pickers. */
export const SYNC_OP_VALUES = ["upsert", "delete"] as const;
