// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/sync-conflict-resolution.json

/**
 * How a dirty-vs-newer-remote conflict resolves (mirrors zed-sync `ConflictResolution`).
 */
export type SyncConflictResolution = "server_wins" | "last_write_wins";

/** Every `SyncConflictResolution` value, in schema order — for validation and pickers. */
export const SYNC_CONFLICT_RESOLUTION_VALUES = ["server_wins", "last_write_wins"] as const;
