// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/version-metadata.json

/**
 * On-the-wire formats for published package artifacts.
 */
export type ArtifactFormat = "tar.gz" | "zip";

/** Every `ArtifactFormat` value, in schema order — for validation and pickers. */
export const ARTIFACT_FORMAT_VALUES = ["tar.gz", "zip"] as const;

export interface VersionMetadata {
  /** Absolute or registry-relative URL the artifact can be fetched from. */
  readonly download_url: string;
  readonly format?: ArtifactFormat;
  readonly name: string;
  readonly org: string;
  /** RFC 3339 timestamp. */
  readonly published_at: string;
  readonly sha256: string;
  readonly size: number;
  readonly vcs_commit?: string | null;
  readonly vcs_tag: string;
  readonly version: string;
  readonly yanked?: boolean;
}
