// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/yank-request.json

/** Body for the yank route. `yanked: false` restores a yanked version. */
export interface YankRequest {
  readonly yanked: boolean;
}
