// GENERATED by codegen/generate.mjs from schemas/ — do not edit by hand.
// Regenerate with `npm run codegen` after changing the Rust types.
// Source: schemas/yank-response.json

export interface YankResponse {
  readonly name: string;
  readonly org: string;
  readonly version: string;
  readonly yanked: boolean;
}
